/**
 * Deploy bundles: a release's Workers, prebuilt, and the manifest that says how
 * to install them into somebody's Cloudflare account through the API alone
 * ([docs/deploy-bundles.md](../../../docs/deploy-bundles.md)).
 *
 * Everything here is pure, and uses nothing a browser lacks, because the deploy
 * page runs it too. The bundle is built once per release from the simple
 * profile (`scripts/build-deploy-bundle.ts`); what differs per install is the
 * install name, the hostnames, two Access vars and the secrets, and every one of
 * those is filled in here, from the manifest, by the deployer.
 */

/** Where an install's own name goes in every name the manifest templates. */
export const INSTALL_TOKEN_V1 = "{install}";

/**
 * What an install name may be. It prefixes every Worker, bucket, index and
 * container application, so it has to leave room for the longest suffix
 * (`-application-artifacts`) under R2's 63 characters.
 */
export const INSTALL_NAME_PATTERN_V1 = "^[a-z][a-z0-9-]{0,30}[a-z0-9]$";

/**
 * The prefix a bundle is generated under, and then replaced by the token. A
 * name the generator derives is taken as it derived it, so the templates cannot
 * drift from what `bun run deployment:config` writes for the same prefix.
 */
export const BUNDLE_SENTINEL_PREFIX_V1 = "zzfrockbotinstallzz";

/** The vars a simple install supplies itself, carried as `vars` not secrets. */
export const INSTALL_VARS_V1 = ["ACCESS_TEAM_DOMAIN", "ACCESS_AUD"] as const;

export const BUNDLE_WORKERS_V1 = [
  "app",
  "computerHost",
  "appletBuild",
] as const;
export type BundleWorkerKeyV1 = (typeof BUNDLE_WORKERS_V1)[number];

/**
 * The order a deploy takes: the app's service bindings name the other two, so
 * a version of it cannot be created until they exist, and a stale host serving
 * a current app is the failure ADR 0004 names.
 */
export const BUNDLE_DEPLOY_ORDER_V1: readonly BundleWorkerKeyV1[] = [
  "computerHost",
  "appletBuild",
  "app",
];

/** One binding, in the shape the Workers script upload API takes. */
export interface BundleBindingV1 {
  readonly type: string;
  readonly name: string;
  readonly [field: string]: unknown;
}

export interface BundleModuleV1 {
  readonly name: string;
  readonly type: "esm" | "commonjs" | "compiled-wasm" | "text" | "buffer";
  /** Where the bytes are, inside the bundle archive. */
  readonly path: string;
  readonly sha256: string;
  readonly size: number;
}

export interface BundleAssetFileV1 {
  /** The path it is served at, with a leading slash. */
  readonly path: string;
  /** Where the bytes are, inside the bundle archive. */
  readonly archivePath: string;
  /**
   * The Workers assets hash: BLAKE3 over the base64 of the bytes and the
   * extension, first 32 hex characters. Precomputed, so a deployer needs no
   * BLAKE3 of its own.
   */
  readonly hash: string;
  readonly size: number;
  readonly contentType: string;
}

export interface BundleSecretV1 {
  readonly name: string;
  /** A first install without it is refused. An update keeps the one set. */
  readonly required: boolean;
  /** Generated by the deployer rather than asked for, and never regenerated. */
  readonly mint?: "hex" | "keyring";
  /** Shared with another Worker in the install, which holds the same value. */
  readonly sharedWith?: readonly BundleWorkerKeyV1[];
  /** Required only by an install that deploys this optional Worker too. */
  readonly requiredWith?: BundleWorkerKeyV1;
}

export interface BundleContainerV1 {
  readonly className: string;
  /** The container application's name, templated. */
  readonly name: string;
  readonly image: string;
  readonly instanceType: string;
  readonly maxInstances: number;
}

/** A Durable Object migration exactly as wrangler's config writes it. */
export interface BundleMigrationV1 {
  readonly tag: string;
  readonly new_classes?: readonly string[];
  readonly new_sqlite_classes?: readonly string[];
  readonly renamed_classes?: readonly { from: string; to: string }[];
  readonly deleted_classes?: readonly string[];
  readonly transferred_classes?: readonly unknown[];
}

export interface BundleWorkerV1 {
  /** The script name, templated. */
  readonly name: string;
  /** Deployed only when the install chooses it (its own Computer host). */
  readonly optional: boolean;
  /** sha256 over this entry with this field left out. */
  readonly contentHash: string;
  readonly mainModule: string;
  readonly modules: readonly BundleModuleV1[];
  readonly compatibilityDate: string;
  readonly compatibilityFlags: readonly string[];
  /** Every binding but the secrets and the install's vars, names templated. */
  readonly bindings: readonly BundleBindingV1[];
  readonly installVars: readonly string[];
  readonly secrets: readonly BundleSecretV1[];
  readonly migrations: readonly BundleMigrationV1[];
  readonly containers: readonly BundleContainerV1[];
  readonly assets?: {
    readonly config: Readonly<Record<string, unknown>>;
    readonly headers?: string;
    readonly redirects?: string;
    readonly files: readonly BundleAssetFileV1[];
  };
  readonly workersDev: boolean;
  /** The install's hostnames are this Worker's custom domains. */
  readonly customDomains: boolean;
  readonly observability?: Readonly<Record<string, unknown>>;
}

export interface DeployBundleManifestV1 {
  readonly schemaVersion: 1;
  readonly kind: "frockbot-deploy-bundle";
  /** The release version, without a `v`. */
  readonly version: string;
  readonly profile: "simple";
  /** The client protocol range this server speaks. */
  readonly protocol: { readonly min: number; readonly max: number };
  /** The archive that holds every `path` below, and its sha256. */
  readonly archive: { readonly file: string; readonly sha256: string };
  readonly install: { readonly token: string; readonly pattern: string };
  readonly resources: {
    readonly r2Buckets: readonly string[];
    readonly vectorizeIndexes: readonly {
      readonly name: string;
      readonly dimensions: number;
      readonly metric: "cosine" | "euclidean" | "dot-product";
    }[];
  };
  readonly applicationArtifact: {
    readonly path: string;
    readonly sha256: string;
    readonly bucket: string;
    readonly key: string;
  };
  readonly workers: Readonly<Record<BundleWorkerKeyV1, BundleWorkerV1>>;
}

/* ── From a generated wrangler config ───────────────────────────────────── */

/**
 * The top-level config keys a bundle knows how to carry. A key outside this
 * list refuses the build: a new binding kind in a tracked `wrangler.jsonc` must
 * be taught here, or the bundle would deploy a Worker without it.
 */
const KNOWN_CONFIG_KEYS_V1 = new Set([
  "$schema",
  "name",
  "main",
  "account_id",
  "compatibility_date",
  "compatibility_flags",
  "assets",
  "worker_loaders",
  "services",
  "r2_buckets",
  "vectorize",
  "ai",
  "analytics_engine_datasets",
  "durable_objects",
  "migrations",
  "vars",
  "observability",
  "routes",
  "workers_dev",
  "containers",
  "alias",
  "send_email",
]);

function templated(value: unknown, what: string): string {
  if (typeof value !== "string" || value === "") {
    throw new Error(`${what} names nothing`);
  }
  return value.replaceAll(BUNDLE_SENTINEL_PREFIX_V1, INSTALL_TOKEN_V1);
}

/** Wrangler's own renames of the legacy instance types. */
function canonicalInstanceTypeV1(type: string): string {
  return type === "standard" ? "standard-1" : type === "dev" ? "lite" : type;
}

function records(value: unknown): Record<string, unknown>[] {
  return Array.isArray(value)
    ? value.filter(
        (entry): entry is Record<string, unknown> =>
          typeof entry === "object" && entry !== null && !Array.isArray(entry),
      )
    : [];
}

/**
 * A bundle Worker's bindings and settings, from the config the generator wrote
 * for the bundle's sentinel profile. Modules, assets, secrets and the content
 * hash are the build's to add.
 */
export function bundleWorkerShapeV1(
  worker: BundleWorkerKeyV1,
  config: Readonly<Record<string, unknown>>,
): Omit<
  BundleWorkerV1,
  "contentHash" | "mainModule" | "modules" | "secrets" | "assets"
> {
  const unknown = Object.keys(config).filter(
    (key) => !KNOWN_CONFIG_KEYS_V1.has(key),
  );
  if (unknown.length > 0) {
    throw new Error(
      `${worker}'s config carries ${unknown.join(", ")}, which a deploy bundle does not know how to deploy. Teach bundle.ts, or the bundle would ship a Worker without it.`,
    );
  }
  const name = templated(config.name, `${worker}'s name`);
  const bindings: BundleBindingV1[] = [];
  for (const loader of records(config.worker_loaders)) {
    bindings.push({ type: "worker_loader", name: String(loader.binding) });
  }
  for (const service of records(config.services)) {
    bindings.push({
      type: "service",
      name: String(service.binding),
      service: templated(service.service, `service ${service.binding}`),
      ...(service.entrypoint === undefined
        ? {}
        : { entrypoint: service.entrypoint }),
    });
  }
  for (const bucket of records(config.r2_buckets)) {
    bindings.push({
      type: "r2_bucket",
      name: String(bucket.binding),
      bucket_name: templated(bucket.bucket_name, `bucket ${bucket.binding}`),
    });
  }
  for (const index of records(config.vectorize)) {
    bindings.push({
      type: "vectorize",
      name: String(index.binding),
      index_name: templated(index.index_name, `index ${index.binding}`),
    });
  }
  if (typeof config.ai === "object" && config.ai !== null) {
    bindings.push({
      type: "ai",
      name: String((config.ai as { binding?: unknown }).binding),
    });
  }
  for (const dataset of records(config.analytics_engine_datasets)) {
    bindings.push({
      type: "analytics_engine",
      name: String(dataset.binding),
      dataset: templated(dataset.dataset, `dataset ${dataset.binding}`),
    });
  }
  const durableObjects = records(
    (config.durable_objects as { bindings?: unknown } | undefined)?.bindings,
  );
  for (const namespace of durableObjects) {
    if (namespace.script_name !== undefined) {
      throw new Error(
        `${worker} binds ${namespace.name} from another script, which a bundle does not deploy`,
      );
    }
    bindings.push({
      type: "durable_object_namespace",
      name: String(namespace.name),
      class_name: String(namespace.class_name),
    });
  }
  for (const email of records(config.send_email)) {
    bindings.push({ type: "send_email", name: String(email.name) });
  }
  const vars = (config.vars ?? {}) as Record<string, unknown>;
  const installVars: string[] = [];
  for (const [key, value] of Object.entries(vars)) {
    if ((INSTALL_VARS_V1 as readonly string[]).includes(key)) {
      installVars.push(key);
      continue;
    }
    if (typeof value !== "string") {
      throw new Error(`${worker}'s var ${key} is not a string`);
    }
    bindings.push({ type: "plain_text", name: key, text: value });
  }

  const containers = records(config.containers).map((container) => {
    const className = String(container.class_name);
    const image = String(container.image);
    if (!/^[a-z0-9.-]+\.[a-z]+\/.+:.+$/.test(image)) {
      throw new Error(
        `${worker}'s container ${className} is built from ${image}; a bundle pulls a published image`,
      );
    }
    return {
      className,
      // Wrangler's own default for a container with no name, so an install
      // wrangler created and one the bundle created are the same application.
      name: `${name}-${className.toLowerCase()}`,
      image,
      instanceType: canonicalInstanceTypeV1(
        String(container.instance_type ?? "lite"),
      ),
      maxInstances: Number(container.max_instances ?? 20),
    };
  });

  const routes = records(config.routes);
  if (routes.some((route) => route.custom_domain !== true)) {
    throw new Error(
      `${worker} has a zone route; a bundle deploys custom domains`,
    );
  }
  const shape = {
    name,
    optional: worker === "computerHost",
    compatibilityDate: String(config.compatibility_date),
    compatibilityFlags: [
      ...((config.compatibility_flags as string[] | undefined) ?? []),
    ],
    bindings,
    installVars,
    migrations: records(config.migrations) as unknown as BundleMigrationV1[],
    containers,
    workersDev: routes.length === 0 && config.workers_dev !== false,
    customDomains: routes.length > 0,
    ...(config.observability === undefined
      ? {}
      : {
          observability: config.observability as Record<string, unknown>,
        }),
  };
  if (JSON.stringify(shape).includes(BUNDLE_SENTINEL_PREFIX_V1)) {
    throw new Error(
      `${worker}'s config names the install in a field bundle.ts does not template`,
    );
  }
  return shape;
}

/* ── Hashing ────────────────────────────────────────────────────────────── */

/** JSON with every object's keys sorted, so equal values hash equally. */
export function canonicalJsonV1(value: unknown): string {
  if (Array.isArray(value)) {
    return `[${value.map((entry) => canonicalJsonV1(entry)).join(",")}]`;
  }
  if (typeof value === "object" && value !== null) {
    const entries = Object.entries(value as Record<string, unknown>)
      .filter(([, entry]) => entry !== undefined)
      .sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0));
    return `{${entries
      .map(([key, entry]) => `${JSON.stringify(key)}:${canonicalJsonV1(entry)}`)
      .join(",")}}`;
  }
  return JSON.stringify(value);
}

export async function sha256HexV1(bytes: Uint8Array | string): Promise<string> {
  const data =
    typeof bytes === "string" ? new TextEncoder().encode(bytes) : bytes;
  const digest = await crypto.subtle.digest(
    "SHA-256",
    data as Uint8Array<ArrayBuffer>,
  );
  return [...new Uint8Array(digest)]
    .map((byte) => byte.toString(16).padStart(2, "0"))
    .join("");
}

/** A Worker's content hash: everything that is deployed, and nothing else. */
export async function workerContentHashV1(
  worker: Omit<BundleWorkerV1, "contentHash">,
): Promise<string> {
  return sha256HexV1(canonicalJsonV1(worker));
}

/* ── Install names ──────────────────────────────────────────────────────── */

export function checkInstallNameV1(name: string): void {
  if (!new RegExp(INSTALL_NAME_PATTERN_V1).test(name)) {
    throw new Error(
      `"${name}" is not an install name: lowercase letters, digits and dashes, starting with a letter, at most 32 characters`,
    );
  }
}

/** A templated name, for one install. */
export function installNameOfV1(template: string, install: string): string {
  return template.replaceAll(INSTALL_TOKEN_V1, install);
}

/** Every name an install owns, which is what an update must land on again. */
export function installIdentityV1(
  manifest: DeployBundleManifestV1,
  install: string,
): {
  workers: Record<BundleWorkerKeyV1, string>;
  r2Buckets: string[];
  vectorizeIndexes: string[];
  containers: string[];
} {
  checkInstallNameV1(install);
  const workers = Object.fromEntries(
    BUNDLE_WORKERS_V1.map((key) => [
      key,
      installNameOfV1(manifest.workers[key].name, install),
    ]),
  ) as Record<BundleWorkerKeyV1, string>;
  return {
    workers,
    r2Buckets: manifest.resources.r2Buckets.map((name) =>
      installNameOfV1(name, install),
    ),
    vectorizeIndexes: manifest.resources.vectorizeIndexes.map((index) =>
      installNameOfV1(index.name, install),
    ),
    containers: BUNDLE_WORKERS_V1.flatMap((key) =>
      manifest.workers[key].containers.map((container) =>
        installNameOfV1(container.name, install),
      ),
    ),
  };
}

/* ── Durable Object migrations ──────────────────────────────────────────── */

/** The classes that hold a namespace once every migration has run. */
export function liveClassesV1(
  migrations: readonly BundleMigrationV1[],
): Set<string> {
  const live = new Set<string>();
  for (const migration of migrations) {
    for (const name of migration.new_classes ?? []) live.add(name);
    for (const name of migration.new_sqlite_classes ?? []) live.add(name);
    for (const { from, to } of migration.renamed_classes ?? []) {
      live.delete(from);
      live.add(to);
    }
    for (const name of migration.deleted_classes ?? []) live.delete(name);
  }
  return live;
}

/** Every class any migration has ever named. */
function knownClassesV1(migrations: readonly BundleMigrationV1[]): Set<string> {
  const known = new Set<string>();
  for (const migration of migrations) {
    for (const name of [
      ...(migration.new_classes ?? []),
      ...(migration.new_sqlite_classes ?? []),
      ...(migration.deleted_classes ?? []),
    ]) {
      known.add(name);
    }
    for (const { from, to } of migration.renamed_classes ?? []) {
      known.add(from);
      known.add(to);
    }
  }
  return known;
}

export interface MigrationUploadV1 {
  readonly old_tag?: string;
  readonly new_tag: string;
  readonly steps: readonly Omit<BundleMigrationV1, "tag">[];
}

/**
 * The migrations an upload carries, given the tag the deployed script is at:
 * everything after it, or nothing when it is current. A tag the bundle does not
 * know is refused rather than guessed at, which is where wrangler would warn
 * and send every step: that script's namespaces came from somewhere else, and
 * replaying this bundle's history over them is how data is lost.
 */
export function migrationUploadV1(
  migrations: readonly BundleMigrationV1[],
  deployedTag: string | undefined,
): MigrationUploadV1 | undefined {
  if (migrations.length === 0) return undefined;
  const steps = (from: number) =>
    migrations.slice(from).map(({ tag: _tag, ...step }) => step);
  const last = migrations[migrations.length - 1]!.tag;
  if (deployedTag === undefined) return { new_tag: last, steps: steps(0) };
  const index = migrations.findIndex(
    (migration) => migration.tag === deployedTag,
  );
  if (index === -1) {
    throw new Error(
      `The deployed script is at migration ${deployedTag}, which this bundle's history (${migrations.map((migration) => migration.tag).join(", ")}) does not contain`,
    );
  }
  if (index === migrations.length - 1) return undefined;
  return { old_tag: deployedTag, new_tag: last, steps: steps(index + 1) };
}

/* ── The equivalence gate ───────────────────────────────────────────────── */

/**
 * Why `next` cannot be deployed over an install of `previous`, or nothing.
 *
 * A Worker name, Durable Object class or migration tag that differs on deploy
 * is a new namespace, which is data loss (ADR 0028). So between two releases:
 * every Worker and resource keeps its templated name, every binding to durable
 * data keeps its target, and the migration history only grows at the end.
 * `release.yml` runs this against the previous release's manifest before it
 * attaches a bundle.
 */
export function bundleSuccessionProblemsV1(
  previous: DeployBundleManifestV1,
  next: DeployBundleManifestV1,
): string[] {
  const problems: string[] = [];
  if (previous.install.token !== next.install.token) {
    problems.push(
      `the install token changed from ${previous.install.token} to ${next.install.token}`,
    );
  }
  for (const bucket of previous.resources.r2Buckets) {
    if (!next.resources.r2Buckets.includes(bucket)) {
      problems.push(`the R2 bucket ${bucket} is no longer created`);
    }
  }
  for (const index of previous.resources.vectorizeIndexes) {
    const kept = next.resources.vectorizeIndexes.find(
      (candidate) => candidate.name === index.name,
    );
    if (!kept) {
      problems.push(`the Vectorize index ${index.name} is no longer created`);
    } else if (
      kept.dimensions !== index.dimensions ||
      kept.metric !== index.metric
    ) {
      problems.push(
        `the Vectorize index ${index.name} changed shape, which rejects every stored vector`,
      );
    }
  }
  for (const key of BUNDLE_WORKERS_V1) {
    const before = previous.workers[key];
    const after = next.workers[key];
    if (before.name !== after.name) {
      problems.push(
        `${key} is renamed from ${before.name} to ${after.name}, a new script with none of its Durable Objects`,
      );
    }
    const history = after.migrations.slice(0, before.migrations.length);
    if (canonicalJsonV1(history) !== canonicalJsonV1(before.migrations)) {
      problems.push(
        `${key}'s migrations (${before.migrations.map((migration) => migration.tag).join(", ")}) are not a prefix of the next release's (${after.migrations.map((migration) => migration.tag).join(", ")}); history may only grow at its end`,
      );
    }
    for (const binding of before.bindings) {
      const target = durableTargetV1(binding);
      if (target === undefined) continue;
      const kept = after.bindings.find(
        (candidate) =>
          candidate.name === binding.name && candidate.type === binding.type,
      );
      if (kept && durableTargetV1(kept) !== target) {
        problems.push(
          `${key}'s ${binding.name} moves from ${target} to ${durableTargetV1(kept)}`,
        );
      }
    }
    for (const container of before.containers) {
      const kept = after.containers.find(
        (candidate) => candidate.className === container.className,
      );
      if (kept && kept.name !== container.name) {
        problems.push(
          `${key}'s container application ${container.name} is renamed to ${kept.name}`,
        );
      }
    }
  }
  return problems;
}

/** What a binding holds durable data in, or undefined for one that holds none. */
function durableTargetV1(binding: BundleBindingV1): string | undefined {
  switch (binding.type) {
    case "r2_bucket":
      return `bucket ${String(binding.bucket_name)}`;
    case "vectorize":
      return `index ${String(binding.index_name)}`;
    case "analytics_engine":
      return `dataset ${String(binding.dataset)}`;
    default:
      return undefined;
  }
}

/** What the account already holds, as far as the install gate reads it. */
export interface DeployedInstallV1 {
  /** Per script name: its migration tag, or null when it has none. */
  readonly scripts: Readonly<Record<string, string | null>>;
  readonly namespaces: readonly {
    readonly script: string;
    readonly class: string;
  }[];
}

/**
 * Why this bundle cannot be deployed over what the account holds, or nothing.
 *
 * The same gate against the live install: a script at a migration tag this
 * bundle's history lacks, or a namespace whose class the history never named,
 * belongs to something else — an older lineage, a newer release, a hand deploy
 * — and deploying over it would orphan data.
 */
export function installSuccessionProblemsV1(
  manifest: DeployBundleManifestV1,
  install: string,
  deployed: DeployedInstallV1,
  workers: readonly BundleWorkerKeyV1[] = BUNDLE_WORKERS_V1,
): string[] {
  const problems: string[] = [];
  for (const key of workers) {
    const worker = manifest.workers[key];
    const script = installNameOfV1(worker.name, install);
    if (!(script in deployed.scripts)) continue;
    const tag = deployed.scripts[script];
    const tags = worker.migrations.map((migration) => migration.tag);
    if (tag !== null && !tags.includes(tag)) {
      problems.push(
        `${script} is at migration ${tag}, which ${manifest.version}'s history (${tags.join(", ")}) does not contain: it was deployed from somewhere else or from a newer release`,
      );
    }
    if (tag === null && tags.length > 0) {
      const held = deployed.namespaces.filter(
        (namespace) => namespace.script === script,
      );
      if (held.length > 0) {
        problems.push(
          `${script} holds Durable Objects (${held.map((namespace) => namespace.class).join(", ")}) but no migration tag, so no history can be applied over it`,
        );
      }
    }
    const known = knownClassesV1(worker.migrations);
    for (const namespace of deployed.namespaces) {
      if (namespace.script === script && !known.has(namespace.class)) {
        problems.push(
          `${script} holds a ${namespace.class} namespace that ${manifest.version} never names`,
        );
      }
    }
  }
  return problems;
}

/* ── The upload ─────────────────────────────────────────────────────────── */

/** The values one install supplies. */
export interface InstallV1 {
  readonly accountId: string;
  readonly name: string;
  /** The app's custom domains. */
  readonly hostnames: readonly string[];
  /** Whether the install runs its own Computer host, on its own Fly account. */
  readonly computerHost: boolean;
  readonly vars: Readonly<Record<string, string>>;
  readonly secrets: Readonly<Record<string, string>>;
  /** An R2 location hint for the buckets it creates. */
  readonly location?: string;
}

/** Which Workers an install deploys, in deploy order. */
export function installWorkersV1(install: InstallV1): BundleWorkerKeyV1[] {
  return BUNDLE_DEPLOY_ORDER_V1.filter(
    (key) => key !== "computerHost" || install.computerHost,
  );
}

/**
 * The `metadata` part of one Worker's script upload.
 *
 * Secrets the install supplies are set; the ones it does not are kept from
 * the deployed script (`keep_bindings`), so an update needs none of them. The
 * app's `COMPUTER_HOST` binding goes when the install runs no Computer host:
 * the Worker reads it as optional, and a binding to a script that does not
 * exist refuses the upload.
 */
export function workerUploadMetadataV1(
  manifest: DeployBundleManifestV1,
  key: BundleWorkerKeyV1,
  install: InstallV1,
  options: {
    readonly migrations?: MigrationUploadV1;
    readonly assetsJwt?: string;
  } = {},
): Record<string, unknown> {
  const worker = manifest.workers[key];
  const skippedScripts = new Set(
    install.computerHost
      ? []
      : [installNameOfV1(manifest.workers.computerHost.name, install.name)],
  );
  const bindings: Record<string, unknown>[] = [];
  for (const binding of worker.bindings) {
    const resolved = Object.fromEntries(
      Object.entries(binding).map(([field, value]) => [
        field,
        typeof value === "string"
          ? installNameOfV1(value, install.name)
          : value,
      ]),
    ) as BundleBindingV1;
    if (
      resolved.type === "service" &&
      skippedScripts.has(String(resolved.service))
    ) {
      continue;
    }
    bindings.push(resolved);
  }
  for (const name of worker.installVars) {
    const text = install.vars[name];
    if (text === undefined || text === "") {
      throw new Error(`The install supplies no ${name}`);
    }
    bindings.push({ type: "plain_text", name, text });
  }
  for (const secret of worker.secrets) {
    const text = install.secrets[secret.name];
    if (text !== undefined && text !== "") {
      bindings.push({ type: "secret_text", name: secret.name, text });
    }
  }
  const assets = worker.assets;
  if (assets && !options.assetsJwt) {
    throw new Error(`${key} serves assets, and no upload session completed`);
  }
  return {
    main_module: worker.mainModule,
    compatibility_date: worker.compatibilityDate,
    compatibility_flags: worker.compatibilityFlags,
    bindings,
    keep_bindings: ["secret_text", "secret_key"],
    ...(options.migrations ? { migrations: options.migrations } : {}),
    ...(worker.containers.length > 0
      ? {
          containers: worker.containers.map((container) => ({
            class_name: container.className,
          })),
        }
      : {}),
    ...(assets
      ? {
          assets: {
            jwt: options.assetsJwt,
            config: {
              ...assets.config,
              ...(assets.headers === undefined
                ? {}
                : { _headers: assets.headers }),
              ...(assets.redirects === undefined
                ? {}
                : { _redirects: assets.redirects }),
            },
          },
        }
      : {}),
    ...(worker.observability ? { observability: worker.observability } : {}),
    annotations: {
      "workers/message": `FrockBot ${manifest.version} deploy bundle`,
      "workers/tag": manifest.version,
    },
  };
}

/**
 * The required secrets a first install of `key` is missing. An update is
 * never refused for these: `keep_bindings` keeps the ones already set.
 */
export function missingSecretsV1(
  manifest: DeployBundleManifestV1,
  key: BundleWorkerKeyV1,
  install: InstallV1,
): string[] {
  const deployed = installWorkersV1(install);
  return manifest.workers[key].secrets
    .filter(
      (secret) =>
        secret.required &&
        (secret.requiredWith === undefined ||
          deployed.includes(secret.requiredWith)) &&
        (install.secrets[secret.name] ?? "") === "",
    )
    .map((secret) => secret.name);
}

/** The manifest, checked for the shape this module reads. */
export function decodeBundleManifestV1(value: unknown): DeployBundleManifestV1 {
  const manifest = value as Partial<DeployBundleManifestV1> | null;
  if (
    typeof manifest !== "object" ||
    manifest === null ||
    manifest.kind !== "frockbot-deploy-bundle" ||
    manifest.schemaVersion !== 1 ||
    typeof manifest.version !== "string" ||
    typeof manifest.workers !== "object" ||
    manifest.workers === null ||
    BUNDLE_WORKERS_V1.some((key) => !manifest.workers?.[key])
  ) {
    throw new Error("Not a FrockBot deploy bundle manifest (schema 1)");
  }
  return manifest as DeployBundleManifestV1;
}

/** The release asset names for one version. */
export function bundleAssetNamesV1(version: string): {
  manifest: string;
  archive: string;
} {
  return {
    manifest: `frockbot-deploy-${version}.json`,
    archive: `frockbot-deploy-${version}.tar.gz`,
  };
}
