// Generated by scripts/generate-isolate-context-catalog.ts. Do not edit.
export const BOT_ISOLATE_CONTEXT_DTS_V1 =
  "/**\n * The common exact `ctx` passed to a Bot-authored Package's tool and hook.\n * The model-facing declarations are generated from these interfaces, and the\n * wrapper's implementation is compile- and test-checked against the same\n * keys.\n */\ninterface BotPackageContextV1 {\n    readonly tool?: string;\n    readonly event?: BotIsolateHookEventNameV1;\n    readonly botId: string;\n    readonly sessionId: string;\n    readonly runId: string;\n    readonly turnId: string;\n    readonly generationId: string;\n    readonly packageId: string;\n    readonly deadlineMs: number;\n    readonly bindings: string[];\n    listCapabilities(): Promise<IsolateCapabilityListOutcomeV1>;\n    requestAuthority(request: IsolateAuthorityRequestV1): Promise<IsolateAuthorityOutcomeV1>;\n    invokeModel(request: NormalizedModelRequest): Promise<BotPackageModelOutcomeV1>;\n}\n\ninterface BotPackageExecutionContextV1 extends BotPackageContextV1 {\n    readonly tool: string;\n    readonly event?: never;\n}\n\ninterface BotPackageHookContextV1 extends BotPackageContextV1 {\n    readonly tool?: never;\n    readonly event: BotIsolateHookEventNameV1;\n}";
export const BOT_ISOLATE_CONTEXT_KEYS_V1 = [
  "tool",
  "event",
  "botId",
  "sessionId",
  "runId",
  "turnId",
  "generationId",
  "packageId",
  "deadlineMs",
  "bindings",
  "listCapabilities",
  "requestAuthority",
  "invokeModel",
] as const;
export const BOT_ISOLATE_CONTEXT_SUMMARY_V1 =
  "Package execute and hook ctx share: readonly tool?: string; readonly event?: BotIsolateHookEventNameV1; readonly botId: string; readonly sessionId: string; readonly runId: string; readonly turnId: string; readonly generationId: string; readonly packageId: string; readonly deadlineMs: number; readonly bindings: string[]; listCapabilities(): Promise<IsolateCapabilityListOutcomeV1>; requestAuthority(request: IsolateAuthorityRequestV1): Promise<IsolateAuthorityOutcomeV1>; invokeModel(request: NormalizedModelRequest): Promise<BotPackageModelOutcomeV1>;";
