// Generated by scripts/generate-isolate-context-catalog.ts. Do not edit.
export const BOT_ISOLATE_CONTEXT_DTS_V1 =
  "/**\n * The exact `ctx` passed to a Bot-authored Package's\n * `execute(tool, input, ctx)`. The model-facing declaration is generated from\n * this interface, and the wrapper's implementation is compile- and test-\n * checked against the same keys.\n */\ninterface BotPackageExecutionContextV1 {\n    readonly tool: string;\n    readonly botId: string;\n    readonly sessionId: string;\n    readonly runId: string;\n    readonly turnId: string;\n    readonly generationId: string;\n    readonly packageId: string;\n    readonly deadlineMs: number;\n    readonly bindings: string[];\n    listCapabilities(): Promise<IsolateCapabilityListOutcomeV1>;\n    requestAuthority(request: IsolateAuthorityRequestV1): Promise<IsolateAuthorityOutcomeV1>;\n    invokeModel(request: NormalizedModelRequest): Promise<BotPackageModelOutcomeV1>;\n}";
export const BOT_ISOLATE_CONTEXT_KEYS_V1 = [
  "tool",
  "botId",
  "sessionId",
  "runId",
  "turnId",
  "generationId",
  "packageId",
  "deadlineMs",
  "bindings",
  "listCapabilities",
  "requestAuthority",
  "invokeModel",
] as const;
export const BOT_ISOLATE_CONTEXT_SUMMARY_V1 =
  "Package execute ctx: readonly tool: string; readonly botId: string; readonly sessionId: string; readonly runId: string; readonly turnId: string; readonly generationId: string; readonly packageId: string; readonly deadlineMs: number; readonly bindings: string[]; listCapabilities(): Promise<IsolateCapabilityListOutcomeV1>; requestAuthority(request: IsolateAuthorityRequestV1): Promise<IsolateAuthorityOutcomeV1>; invokeModel(request: NormalizedModelRequest): Promise<BotPackageModelOutcomeV1>;";
