import { COMPUTER_TARIFF } from "./computer.js";

export const billingPage = `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Billing · FrockBot</title><link rel="stylesheet" href="/billing.css"><script src="/billing.js" defer></script></head>
<body><main><a class="back" href="/">← Open FrockBot / sign in</a><header><p class="eyebrow">YOUR ACCOUNT</p><h1>Billing & usage</h1><p>One plan. A shared balance for every Bot.</p></header>
<p id="notice" role="status" aria-live="polite">Loading your balance…</p>
<section class="plan"><div><h2>FrockBot</h2><p class="price">US$29 <span>/ month</span></p><p>Includes US$15 of usage credit each billing month.</p><p id="subscription"></p></div><div class="actions"><button id="subscribe" disabled>Subscribe</button><button id="manage" class="secondary" disabled>Manage subscription</button></div></section>
<section class="balances" aria-label="Available credit"><article><h2>Monthly credit</h2><strong id="included">—</strong><p>Resets each billing month. Used first.</p></article><article><h2>Purchased credit</h2><strong id="purchased">—</strong><p>Carries forward for future usage.</p></article><article><h2>Reserved for work</h2><strong id="reserved">—</strong><p>Unused credit returns when the work settles.</p></article></section>
<section><h2>Add a top-up</h2><p>Prepaid credit. No automatic overage charges. A subscription is required to use credit.</p><div class="topups"><button data-topup="1000" disabled>US$10</button><button data-topup="2500" disabled>US$25</button><button data-topup="5000" disabled>US$50</button></div></section>
<section class="explanation"><h2>What uses credit?</h2><p>Hosted models and your cloud computer share this balance. Bring your own model account and pay that provider directly; computer usage still uses FrockBot credit.</p><p>Active Computer time is US$${COMPUTER_TARIFF.activeUsdPerHour.toFixed(2)} per hour, charged from prepaid credit. Up to ${COMPUTER_TARIFF.storageIncludedGb} GB of Computer storage while idle is included in the subscription. The initial viewer window is ${COMPUTER_TARIFF.viewerOpenSeconds} seconds; continued viewing renews in ${COMPUTER_TARIFF.viewerRenewSeconds}-second increments. Other Computer work is charged by its active duration.</p><p>When credit runs out, new paid work pauses and an active viewer is disconnected. Your conversations and account remain accessible. Cancelling stops the next renewal; paid access continues until the end of your billing period.</p></section>
<section><h2>Hosted model rates</h2><p>US dollars per million tokens. Your own model provider sets its own prices.</p><ul id="rates"></ul></section>
<section><h2>Usage by day &amp; Bot</h2><p>Settled charges over the past 31 days.</p><ul id="summaries"></ul></section>
<section><h2>Credit history</h2><ul id="payments"></ul></section>
<section><div class="usage-title"><h2>Recent usage</h2><button id="refresh" class="secondary">Refresh</button></div><p id="empty">No usage yet.</p><div class="table-wrap"><table hidden id="usage"><thead><tr><th>When</th><th>Work</th><th>Bot / conversation</th><th>Status</th><th>Charge</th></tr></thead><tbody></tbody></table></div><button id="more" class="secondary" hidden>Load older usage</button></section>
<footer>All amounts are in US dollars. Any applicable tax is shown at checkout. Payments are securely handled by Stripe.</footer></main></body></html>`;

export const billingStyles = `:root{color-scheme:light;--paper:#faf7f2;--ink:#1e1d27;--muted:#6d6974;--line:#e7e0d9;--accent:#d92d5f}*{box-sizing:border-box}body{margin:0;background:var(--paper);color:var(--ink);font:16px/1.6 system-ui,sans-serif}main{max-width:1000px;margin:auto;padding:36px 24px 64px}a{color:var(--accent)}header{margin:42px 0 30px}h1{font-size:clamp(32px,6vw,48px);letter-spacing:-.04em;margin:0}h2{font-size:20px;margin:0 0 12px}p{color:var(--muted);margin:8px 0}.eyebrow{letter-spacing:.15em;font-size:12px;font-weight:700}.plan,section{padding:28px;border:1px solid var(--line);border-radius:18px;background:#fff;margin:20px 0}.plan{display:flex;justify-content:space-between;align-items:center;gap:24px}.price{font-size:36px;color:var(--ink);font-weight:700}.price span{font-size:16px;font-weight:400}.actions{display:grid;gap:12px}.balances{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:20px;padding:0;border:0;background:transparent}.balances article{min-width:0;border:1px solid var(--line);border-radius:18px;padding:24px;background:#fff}.balances h2{font-size:16px}.balances strong{font-size:30px}.balances p{font-size:14px}button{font:inherit;font-weight:600;border:1px solid var(--accent);border-radius:10px;padding:12px 20px;background:var(--accent);color:#fff;cursor:pointer}button:disabled{opacity:.5;cursor:default}button.secondary{background:transparent;color:var(--accent)}button:focus-visible,a:focus-visible{outline:3px solid #ec386b;outline-offset:4px}.topups{display:flex;gap:12px;flex-wrap:wrap;margin-top:18px}#notice{border-left:3px solid #ec386b;padding:10px 16px;white-space:pre-wrap}.usage-title{display:flex;align-items:center;justify-content:space-between;gap:16px}.table-wrap{overflow:auto}table{width:100%;border-collapse:collapse;font-size:14px}td,th{text-align:left;padding:14px 10px;border-bottom:1px solid var(--line);vertical-align:top;overflow-wrap:anywhere}td small{display:block;color:var(--muted)}footer{color:var(--muted);font-size:13px;margin-top:28px}@media(max-width:650px){main{padding:24px 16px}.balances{grid-template-columns:minmax(0,1fr)}.plan{align-items:stretch;flex-direction:column}section,.plan{padding:22px}.actions{grid-template-columns:minmax(0,1fr)}td,th{min-width:100px}}`;

export const billingScript = `
const el = id => document.getElementById(id);
const money = value => new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',minimumFractionDigits:2,maximumFractionDigits:4}).format(value/1000000);
let state; let busy=false; let cursor;
async function api(path,body){const response=await fetch(path,{credentials:'same-origin',headers:body?{'content-type':'application/json'}:{},...(body?{method:'POST',body:JSON.stringify(body)}:{})});const data=await response.json();if(!response.ok)throw new Error(data.error||'Billing is unavailable. Please try again.');return data;}
function notice(text){el('notice').textContent=text;}
function buttons(){const subscribed=state?.subscription&&!['canceled','incomplete_expired'].includes(state.subscription.status);el('subscribe').disabled=busy||!state?.paymentsAvailable||!!subscribed;el('manage').disabled=busy||!state?.paymentsAvailable||!state?.subscription;document.querySelectorAll('[data-topup]').forEach(b=>b.disabled=busy||!state?.paymentsAvailable||!state?.canSpend||state?.suspended);}
function rows(items,append){const body=el('usage').querySelector('tbody');if(!append)body.replaceChildren();for(const row of items){const tr=document.createElement('tr');const values=[new Date(row.created).toLocaleString(),row.description,[row.botId,row.sessionId].filter(Boolean).join(' / ')||'Account',row.status==='reserved'?'Pending reconciliation':row.status,row.settlement?money(row.settlement.chargeMicros):money(row.reservedMicros)+' reserved'];for(const value of values){const td=document.createElement('td');td.textContent=value;tr.append(td);}if(row.settlement){const detail=document.createElement('details');const label=document.createElement('summary');label.textContent='Usage details';detail.append(label);const quantities=document.createElement('small');quantities.textContent=Object.entries(row.settlement.quantities).map(([key,value])=>key+': '+value.toLocaleString()).join(' · ')||'No billable provider usage';detail.append(quantities);if(row.unitRates){const rates=document.createElement('small');rates.textContent='Recorded rates (micro-US$ per token): '+Object.entries(row.unitRates).map(([key,value])=>key+': '+value).join(' · ');detail.append(rates);}tr.children[1].append(detail);}body.append(tr);}el('usage').hidden=!body.children.length;el('empty').hidden=!!body.children.length;cursor=items.length?Math.min(...items.map(row=>row.cursor)):undefined;el('more').hidden=items.length<100;}
function list(id,values,empty){const target=el(id);target.replaceChildren();for(const text of values.length?values:[empty]){const li=document.createElement('li');li.textContent=text;target.append(li);}}
async function load(append=false){try{const data=await api('/api/billing'+(append&&cursor?'?before='+cursor:''));state=data;el('included').textContent=money(data.includedMicros);el('purchased').textContent=money(data.purchasedMicros);el('reserved').textContent=money(data.reservedMicros);const sub=data.subscription;el('subscription').textContent=sub?sub.status+' · '+(sub.cancelAtPeriodEnd?'Access ends ':'Current period ends ')+new Date(sub.periodEnd).toLocaleDateString():'No subscription yet';rows(data.usage,append);list('rates',Object.entries(data.modelRates||{}).map(([model,rate])=>model+' — input US$'+rate.inputUsdPerMillion+', cached input US$'+rate.cachedInputUsdPerMillion+', output US$'+rate.outputUsdPerMillion),'Hosted model rates are awaiting launch setup.');list('summaries',(data.summaries||[]).map(row=>row.day+' · '+(row.botId||'Account')+' · '+row.kind+' · '+money(row.chargeMicros)),'No settled usage yet.');list('payments',(data.payments||[]).map(row=>new Date(row.created).toLocaleDateString()+' · '+(row.kind==='included'?'Monthly allowance':'Purchased top-up')+' · '+money(row.creditMicros)+(row.expires?' · expires '+new Date(row.expires).toLocaleDateString():'')),'No credit granted yet.');notice(data.suspended?'Payments need review. Contact support before starting more paid work.':!data.paymentsAvailable?'Payments are not available yet. Your account and usage remain accessible.':new URLSearchParams(location.search).get('checkout')==='success'?'Checkout finished. Your verified balance is shown below; a payment may take a moment to appear.':'Your balance is shared across all your Bots.');}catch(error){notice(error.message);}finally{buttons();}}
async function purchase(kind,cents){if(busy)return;busy=true;buttons();const key='frockbot-checkout-'+kind+'-'+(cents||0);let id=sessionStorage.getItem(key)||crypto.randomUUID();sessionStorage.setItem(key,id);try{const result=await api('/api/billing/checkout',{id,kind,...(cents?{cents}:{})});sessionStorage.removeItem(key);location.assign(result.url);}catch(error){notice(error.message);busy=false;buttons();}}
el('subscribe').onclick=()=>purchase('subscription');document.querySelectorAll('[data-topup]').forEach(button=>button.onclick=()=>purchase('topup',Number(button.dataset.topup)));
el('manage').onclick=async()=>{busy=true;buttons();try{const result=await api('/api/billing/portal',{id:crypto.randomUUID()});location.assign(result.url);}catch(error){notice(error.message);busy=false;buttons();}};
el('refresh').onclick=()=>load();el('more').onclick=()=>load(true);load();
`;
