// Turns three authored text files into TypeScript the Worker bundle can carry.
//
// The Applets feature is ordinary first-party code, but three of the things it
// ships are not TypeScript: the SDK scaffold a new Applet starts from, the
// Skill that teaches a Bot to write one, and the two HTML pages the shell
// serves into a sandboxed iframe. A Worker has no filesystem, so each has to
// reach the bundle as a string. That is all this script does.
//
// What it writes:
//
//   applets/template.generated.ts   the SDK scaffold
//   applets/pages.generated.ts      the two pages, with the bridge helper
//                                   inlined and each page's digest
//   packages/plugin-skills/src/managed-applets.generated.ts   the Skill
//
// Freshness is proved by `--check`, which `bun run typecheck` runs.
import { format } from "prettier";

const root = new URL("../", import.meta.url);
const at = (path: string): URL => new URL(path, root);

const TEMPLATE_DIRECTORY = "applets/sdk/template/";
// Written in this order by `applet_create`, so the newest file — the one the
// canvas opens on — is `server.ts`, the file a Bot edits first.
const TEMPLATE_FILES = ["README.md", "applet.json", "ui.tsx", "server.ts"];
const PAGE_IDS = ["list", "canvas"] as const;

const TEMPLATE_OUTPUT = "applets/template.generated.ts";
const PAGES_OUTPUT = "applets/pages.generated.ts";
const SKILL_SOURCE = "applets/skills/applets.md";
const SKILL_OUTPUT = "packages/plugin-skills/src/managed-applets.generated.ts";

/** Content addressing, the same digest the page route verifies against. */
async function sha256Hex(text: string): Promise<string> {
  const digest = await crypto.subtle.digest(
    "SHA-256",
    new TextEncoder().encode(text),
  );
  return [...new Uint8Array(digest)]
    .map((byte) => byte.toString(16).padStart(2, "0"))
    .join("");
}

async function prettyTypeScript(source: string): Promise<string> {
  return await format(source, { parser: "typescript" });
}

/**
 * Emitted into every generated module that carries text: the payloads travel
 * as base64 and are decoded once at load.
 *
 * Applet source, the Skill that teaches it, and the pages that describe it all
 * contain `from "@frockbot/…"` inside string literals. Encoding keeps a text
 * scan over the compiled bundle honest, and keeps a generated module from
 * looking like it imports things it does not.
 */
const DECODE_HELPER = [
  "const TEXT_V1 = new TextDecoder();",
  "function fromBase64V1(value: string): string {",
  "  return TEXT_V1.decode(",
  "    Uint8Array.from(atob(value), (character) => character.charCodeAt(0)),",
  "  );",
  "}",
].join("\n");

function base64(text: string): string {
  return Buffer.from(text, "utf8").toString("base64");
}

async function templateModule(): Promise<string> {
  const files: Array<{ path: string; base64: string }> = [];
  for (const path of TEMPLATE_FILES) {
    const text = await Bun.file(at(`${TEMPLATE_DIRECTORY}${path}`)).text();
    files.push({ path, base64: base64(text) });
  }
  return await prettyTypeScript(
    [
      "// Generated by scripts/build-applets-assets.ts. Do not edit.",
      "//",
      "// The Applets SDK's scaffold, as strings. `applet_create` writes these",
      "// through the Workspace, and a Worker has no filesystem to read them",
      "// from, so the template travels in the bundle rather than beside it.",
      "// Editing `applets/sdk/template/` and rerunning the build is the only",
      "// way to change what a new Applet starts as.",
      "//",
      "// The bodies are base64 because Applet source contains import specifiers",
      "// that a text scan over the compiled bundle would otherwise read as this",
      "// module's own. `feature.ts` decodes them.",
      "export const APPLET_TEMPLATE_FILES_V1: ReadonlyArray<{",
      "  path: string;",
      "  base64: string;",
      `}> = ${JSON.stringify(files, null, 2)};`,
      "",
    ].join("\n"),
  );
}

/** One page, with the versioned bridge helper substituted in. */
async function pageHtml(id: string, helper: string): Promise<string> {
  const source = await Bun.file(at(`applets/pages/${id}.html`)).text();
  // The placeholder is a bare identifier so the page stays valid HTML a
  // formatter can read; Prettier writes it back with a semicolon, so the
  // pattern tolerates one.
  const marker = /^[ \t]*PACKAGE_IFRAME_HELPER_JS_V1;?[ \t]*$/m;
  if (!marker.test(source)) {
    throw new Error(`page "${id}.html" has no bridge helper placeholder`);
  }
  return source.replace(marker, helper);
}

async function pagesModule(): Promise<string> {
  // Imported by path, not by specifier: this script runs from the repository
  // root, where the workspace's package names are not resolvable.
  const { PACKAGE_IFRAME_HELPER_JS_V1 } =
    await import("../core/contracts/iframe-ui.ts");
  const pages: Array<{
    id: string;
    contentHash: string;
    size: number;
    html: string;
  }> = [];
  for (const id of PAGE_IDS) {
    const html = await pageHtml(id, PACKAGE_IFRAME_HELPER_JS_V1);
    pages.push({
      id,
      contentHash: await sha256Hex(html),
      size: new TextEncoder().encode(html).byteLength,
      html,
    });
  }
  return await prettyTypeScript(
    [
      "// Generated by scripts/build-applets-assets.ts. Do not edit.",
      "//",
      "// The Applets Package's two pages, authored at `applets/pages/`, with",
      "// the versioned iframe bridge helper substituted for its placeholder.",
      "// `pages.ts` names the tools each page may call and the slots it mounts",
      "// into.",
      "//",
      "// The digest is what the anonymous page origin serves the bytes under and",
      "// re-verifies before answering, so a page is addressed by its content the",
      "// way a Bot-authored one is.",
      DECODE_HELPER,
      "",
      "export const APPLETS_PAGE_SOURCES_V1: ReadonlyArray<{",
      "  pageId: string;",
      "  contentHash: string;",
      "  size: number;",
      "  html: string;",
      "}> = [",
      ...pages.map(
        (page) =>
          `  { pageId: ${JSON.stringify(page.id)}, contentHash: ${JSON.stringify(
            page.contentHash,
          )}, size: ${page.size}, html: fromBase64V1(${JSON.stringify(
            base64(page.html),
          )}) },`,
      ),
      "];",
      "",
    ].join("\n"),
  );
}

/**
 * The Applets Skill, as a managed Skill document.
 *
 * It is authored in `applets/skills/applets.md`, beside the feature it
 * documents, and copied here into `plugin-skills`'s managed set — string
 * constants compiled into that Package, read-only because there is no path
 * from `skill_write` to one.
 */
async function skillModule(): Promise<string> {
  const text = await Bun.file(at(SKILL_SOURCE)).text();
  return await prettyTypeScript(
    [
      "// Generated by scripts/build-applets-assets.ts. Do not edit.",
      "//",
      "// Authored at applets/skills/applets.md.",
      DECODE_HELPER,
      'export const APPLETS_SKILL_SLUG_V1 = "applets";',
      `export const APPLETS_SKILL_DOCUMENT_V1 = fromBase64V1(${JSON.stringify(base64(text))});`,
      "",
    ].join("\n"),
  );
}

const outputs: Array<[string, () => Promise<string>]> = [
  [TEMPLATE_OUTPUT, templateModule],
  [PAGES_OUTPUT, pagesModule],
  [SKILL_OUTPUT, skillModule],
];

if (process.argv.includes("--check")) {
  for (const [path, build] of outputs) {
    const expected = await build();
    const current = await Bun.file(at(path))
      .text()
      .catch(() => "");
    if (current !== expected) {
      console.error(
        `${path} is stale; run \`bun scripts/build-applets-assets.ts\`.`,
      );
      process.exit(1);
    }
  }
  console.log("Applets assets are fresh.");
} else {
  for (const [path, build] of outputs) await Bun.write(at(path), await build());
  console.log("Built the Applets assets.");
}
