// Builds the Applets Package's immutable artifacts, and only builds them here.
//
// ADR 0022 decision 8 makes `@frockbot/plugin-applets` a Package with no
// in-process code: it ships in the foundation application as an artifact-backed
// member with first-party provenance, so it mounts through the same loader path
// as a Bot-authored Package. Something has to turn its TypeScript and its two
// HTML pages into the immutable, content-addressed bytes that path consumes,
// and "Composition consumes immutable content-addressed artifacts and never
// builds them" says it cannot be Composition. So it is this script, at build
// time, with its output checked in and its freshness proved by `--check` the
// way the isolate context catalog's is.
//
// What it writes:
//
//   packages/plugin-applets/src/template.generated.ts   the SDK template, as
//                                                       strings the isolate can
//                                                       write with no filesystem
//   packages/plugin-applets/frockbot.json               the two page artifact
//                                                       refs, filled in
//   applications/foundation/generated/applets-artifact.ts
//                                                       the module text, both
//                                                       pages, the manifest, and
//                                                       the artifact refs
//   applications/foundation/frockbot.application.json   the member's artifact
//
// The module is bundled with esbuild to a single ESM file with no import at
// all, which is exactly what `apps/cloudflare-bundler` produces for a
// Bot-authored `package.ts` and what `findUnresolvedSpecifier` there insists
// on: the isolate's module map has two entries, the kernel's generated wrapper
// and this.
import { build } from "esbuild";
import { format } from "prettier";

const root = new URL("../", import.meta.url);
const at = (path: string): URL => new URL(path, root);

const TEMPLATE_DIRECTORY = "packages/applet-sdk/template/";
const TEMPLATE_FILES = ["applet.json", "server.ts", "ui.tsx", "README.md"];
const PAGE_IDS = ["list", "canvas"] as const;

const TEMPLATE_OUTPUT = "packages/plugin-applets/src/template.generated.ts";
const MANIFEST_PATH = "packages/plugin-applets/frockbot.json";
const ARTIFACT_OUTPUT = "applications/foundation/generated/applets-artifact.ts";
const SKILL_SOURCE = "packages/plugin-applets/skills/applets.md";
const SKILL_OUTPUT = "packages/plugin-skills/src/managed-applets.generated.ts";
const APPLICATION_PATH = "applications/foundation/frockbot.application.json";
const APPLETS_SPECIFIER = "@frockbot/plugin-applets";
/**
 * Recorded on the artifact, and pinned deliberately.
 *
 * A Bot-authored Package records `@cloudflare/worker-bundler@x`, because that
 * Worker produced its bytes. These bytes were produced here, by esbuild at
 * build time, and saying so is the point: the artifact reference is a record of
 * what made the bytes, and a bump of this string is a re-bundle-everything
 * event exactly as it is for the Worker bundler.
 */
const APPLETS_BUNDLER_VERSION = "frockbot-applets-esbuild@0.28.2";

/** Content addressing, the same digest the bundler and the loader agree on. */
async function sha256Hex(text: string): Promise<string> {
  const digest = await crypto.subtle.digest(
    "SHA-256",
    new TextEncoder().encode(text),
  );
  return [...new Uint8Array(digest)]
    .map((byte) => byte.toString(16).padStart(2, "0"))
    .join("");
}

async function prettyTypeScript(source: string): Promise<string> {
  return await format(source, { parser: "typescript" });
}

async function prettyJson(value: unknown): Promise<string> {
  return await format(JSON.stringify(value), { parser: "json" });
}

async function templateModule(): Promise<string> {
  const files: Array<{ path: string; text: string }> = [];
  for (const path of TEMPLATE_FILES) {
    files.push({
      path,
      text: await Bun.file(at(`${TEMPLATE_DIRECTORY}${path}`)).text(),
    });
  }
  return await prettyTypeScript(
    [
      "// Generated by scripts/build-applets-package.ts. Do not edit.",
      "//",
      "// The Applets SDK's scaffold, as strings. `applet_create` writes these",
      "// through `ctx.workspace.write` from inside a Bot isolate, which has no",
      "// filesystem and no way to read this repository, so the template travels",
      "// in the artifact rather than beside it. Editing",
      "// `packages/applet-sdk/template/` and rerunning the build is the only way",
      "// to change what a new Applet starts as.",
      "export const APPLET_TEMPLATE_FILES_V1: ReadonlyArray<{",
      "  path: string;",
      "  text: string;",
      `}> = ${JSON.stringify(files, null, 2)};`,
      "",
    ].join("\n"),
  );
}

/** The isolate module: one ESM file, no imports, `tools` plus `execute`. */
async function packageModule(): Promise<string> {
  const result = await build({
    entryPoints: [at("packages/plugin-applets/src/package.ts").pathname],
    bundle: true,
    format: "esm",
    platform: "neutral",
    target: "es2022",
    write: false,
    charset: "utf8",
    legalComments: "none",
    logLevel: "silent",
  });
  const output = result.outputFiles?.[0];
  if (!output) throw new Error("esbuild produced no module for package.ts");
  const module = output.text;
  const unresolved = /(?:^|\n)\s*import\s+[^\n]*from\s*["']([^"']+)["']/.exec(
    module,
  );
  if (unresolved) {
    throw new Error(
      `the bundled Applets module still imports "${unresolved[1]}"; the isolate resolves nothing`,
    );
  }
  return module;
}

/** One inline page, with the versioned bridge helper substituted in. */
async function pageHtml(id: string, helper: string): Promise<string> {
  const source = await Bun.file(
    at(`packages/plugin-applets/src/pages/${id}.html`),
  ).text();
  // The placeholder is a bare identifier so the page stays valid HTML a
  // formatter can read; Prettier writes it back with a semicolon, so the
  // pattern tolerates one.
  const marker = /^[ \t]*PACKAGE_IFRAME_HELPER_JS_V1;?[ \t]*$/m;
  if (!marker.test(source)) {
    throw new Error(`page "${id}.html" has no bridge helper placeholder`);
  }
  return source.replace(marker, helper);
}

interface Built {
  templateModule: string;
  skillModule: string;
  manifestJson: string;
  artifactModule: string;
  applicationJson: string;
}

/**
 * The Applets Skill, as a managed Skill document.
 *
 * A Package with no in-process code has nowhere to put a Skill: the manifest
 * declares no `skills` Contribution kind, and the Catalog's Skill index is for
 * Packages a User installed, not for a foundation member. The mechanism that
 * already exists for a first-party Skill is `plugin-skills`'s managed set —
 * string constants compiled into that Package's artifact, pinned by the Turn's
 * `CompositionPinV1.artifactSetHash`, read-only because there is no path from
 * `skill_write` to an artifact. So the Skill is authored in
 * `packages/plugin-applets/skills/applets.md`, where it belongs beside the
 * Package it documents, and this build copies it into the managed set. That is
 * the smallest declared mechanism consistent with ADR 0016: it is still a
 * Package contributing prompt content, not a Workspace file, so the rule about
 * instruction roots is untouched.
 */
async function skillModule(): Promise<string> {
  const text = await Bun.file(at(SKILL_SOURCE)).text();
  return await prettyTypeScript(
    [
      "// Generated by scripts/build-applets-package.ts. Do not edit.",
      "//",
      "// Authored at packages/plugin-applets/skills/applets.md.",
      'export const APPLETS_SKILL_SLUG_V1 = "applets";',
      `export const APPLETS_SKILL_DOCUMENT_V1 = ${JSON.stringify(text)};`,
      "",
    ].join("\n"),
  );
}

async function buildAll(): Promise<Built> {
  // Imported by path, not by specifier: this script runs from the repository
  // root, where the workspace's package names are not resolvable.
  const { PACKAGE_IFRAME_HELPER_JS_V1 } =
    await import("../packages/kernel-contracts/src/iframe-ui.ts");
  const { PACKAGE_UI_ARTIFACT_VERSION } =
    await import("../packages/kernel-contracts/src/authoring.ts");

  const template = await templateModule();
  const module = await packageModule();
  const moduleHash = await sha256Hex(module);

  const pages: Array<{ id: string; html: string; hash: string }> = [];
  for (const id of PAGE_IDS) {
    const html = await pageHtml(id, PACKAGE_IFRAME_HELPER_JS_V1);
    pages.push({ id, html, hash: await sha256Hex(html) });
  }

  const manifest = JSON.parse(
    await Bun.file(at(MANIFEST_PATH)).text(),
  ) as Record<string, unknown>;
  const contributions = manifest.contributions as {
    client: { pages: Array<Record<string, unknown>> };
  };
  for (const page of contributions.client.pages) {
    const built = pages.find((candidate) => candidate.id === page.id);
    if (!built) {
      throw new Error(
        `frockbot.json declares page "${String(page.id)}" with no source`,
      );
    }
    page.artifact = {
      contentHash: built.hash,
      size: new TextEncoder().encode(built.html).byteLength,
      mediaType: "text/html",
      bundlerVersion: PACKAGE_UI_ARTIFACT_VERSION,
    };
  }
  // The tools the isolate exports are the tools the manifest declares: the
  // isolate host refuses a mount whose health report and manifest disagree, so
  // there is one list and the build copies it rather than a person keeping two
  // in step.
  manifest.tools = await declaredTools();

  const artifactRef = {
    contentHash: moduleHash,
    size: new TextEncoder().encode(module).byteLength,
    mediaType: "application/javascript" as const,
    bundlerVersion: APPLETS_BUNDLER_VERSION,
  };

  const application = JSON.parse(
    await Bun.file(at(APPLICATION_PATH)).text(),
  ) as { packages: Array<Record<string, unknown>> };
  const member = application.packages.find(
    (entry) => entry.specifier === APPLETS_SPECIFIER,
  );
  if (!member) {
    throw new Error(
      `${APPLICATION_PATH} does not list ${APPLETS_SPECIFIER}; add it with provenance first-party and this script fills in its artifact`,
    );
  }
  member.artifact = artifactRef;

  const artifactModule = await prettyTypeScript(
    [
      "// Generated by scripts/build-applets-package.ts. Do not edit.",
      "//",
      "// The Applets Package as the loader consumes it: one immutable module,",
      "// two immutable pages, and the manifest that names them. This file is",
      "// the whole reason the Applets Package needs no Contribution table entry",
      "// — the application declares an artifact, and the isolate host does the",
      "// rest.",
      'import type { ArtifactRefV1 } from "@frockbot/kernel-composition/generation";',
      "",
      "/** The `package.js` module the Bot isolate mounts. */",
      `export const APPLETS_PACKAGE_MODULE_V1 = ${JSON.stringify(module)};`,
      "",
      "/** The immutable reference the foundation application's member carries. */",
      `export const APPLETS_PACKAGE_ARTIFACT_V1: ArtifactRefV1 = ${JSON.stringify(artifactRef)};`,
      "",
      "/** Each inline page, by manifest page id. */",
      "export const APPLETS_PACKAGE_PAGES_V1: ReadonlyArray<{",
      "  id: string;",
      "  contentHash: string;",
      "  html: string;",
      `}> = ${JSON.stringify(
        pages.map((page) => ({
          id: page.id,
          contentHash: page.hash,
          html: page.html,
        })),
        null,
        2,
      )};`,
      "",
      "/**",
      " * Every first-party artifact this bundle carries, by content hash.",
      " *",
      " * The store reads `packages/<hash>.mjs` and `packages/<hash>.html` from",
      " * object storage first and falls back to this map, so a first-party",
      " * artifact-backed member needs no deploy step of its own and behaves",
      " * identically in production, in dev, in workerd, and in e2e. Nothing here",
      " * is built at read time: these are the same immutable bytes the build",
      " * produced, addressed by the same digest the loader verifies.",
      " */",
      "export const FIRST_PARTY_PACKAGE_ARTIFACTS_V1: ReadonlyMap<",
      "  string,",
      "  string",
      "> = new Map([",
      `  [${JSON.stringify(`packages/${moduleHash}.mjs`)}, APPLETS_PACKAGE_MODULE_V1],`,
      ...pages.map(
        (page, index) =>
          `  [${JSON.stringify(`packages/${page.hash}.html`)}, APPLETS_PACKAGE_PAGES_V1[${index}]!.html],`,
      ),
      "]);",
      "",
    ].join("\n"),
  );

  return {
    templateModule: template,
    skillModule: await skillModule(),
    manifestJson: await prettyJson(manifest),
    artifactModule,
    applicationJson: await prettyJson(application),
  };
}

/** The manifest's `tools`, read from the module the isolate will actually run. */
async function declaredTools(): Promise<unknown> {
  const module = (await import(
    at("packages/plugin-applets/src/package.ts").pathname
  )) as { tools: Array<Record<string, unknown>> };
  return module.tools.map((tool) => ({
    name: tool.name,
    description: tool.description,
    inputSchema: tool.inputSchema,
  }));
}

const outputs: Array<[string, keyof Built]> = [
  [TEMPLATE_OUTPUT, "templateModule"],
  [SKILL_OUTPUT, "skillModule"],
  [MANIFEST_PATH, "manifestJson"],
  [ARTIFACT_OUTPUT, "artifactModule"],
  [APPLICATION_PATH, "applicationJson"],
];

if (process.argv.includes("--check")) {
  // The template is checked first and on its own: it is an *input* to the
  // bundle, so a stale template would otherwise produce a stale module that
  // matches an equally stale generated file and pass.
  const expectedTemplate = await templateModule();
  const currentTemplate = await Bun.file(at(TEMPLATE_OUTPUT))
    .text()
    .catch(() => "");
  if (currentTemplate !== expectedTemplate) {
    console.error(
      "The Applets Package template is stale; run `bun scripts/build-applets-package.ts`.",
    );
    process.exit(1);
  }
  const built = await buildAll();
  for (const [path, key] of outputs) {
    const current = await Bun.file(at(path))
      .text()
      .catch(() => "");
    if (current !== built[key]) {
      console.error(
        `${path} is stale; run \`bun scripts/build-applets-package.ts\`.`,
      );
      process.exit(1);
    }
  }
  console.log("Applets Package artifacts are fresh.");
} else {
  // Two passes: the first refreshes the template the bundle reads, the second
  // bundles against it.
  await Bun.write(at(TEMPLATE_OUTPUT), await templateModule());
  const built = await buildAll();
  for (const [path, key] of outputs) await Bun.write(at(path), built[key]);
  console.log("Built the Applets Package artifacts.");
}
