// Turns authored text into TypeScript the Worker bundle can carry.
//
// A Worker has no filesystem, so the Plugin scaffold and the managed Skills
// reach the bundle as strings. A Skill is a directory (ADR 0030): its
// `SKILL.md` and whatever Markdown sits under `references/`.
//
// What it writes:
//
//   app/plugins/template.generated.ts       the Plugin SDK scaffold (ADR 0026)
//   app/plugins/skills/plugins/references/types.md
//                                           the Plugin SDK declarations, as
//                                           the Plugins Skill's reference
//   app/skills/managed-plugins.generated.ts the Plugins Skill
//   app/skills/managed-a2ui.generated.ts    the Cards Skill (ADR 0030), whose
//                                           references are themselves built by
//                                           scripts/generate-a2ui-skill.ts
//   app/skills/managed-recipes.generated.ts add-connector, write-skill
//
// Freshness is proved by `--check`, which `bun run typecheck` runs.
import { existsSync, readdirSync } from "node:fs";
import { format } from "prettier";
import {
  SKILL_MAX_FILE_BYTES,
  SKILL_MAX_REFERENCES,
  isSkillReferenceNameV1,
} from "../app/skills/skill-md.ts";
import { SDK_PLUGIN_TYPES } from "../applets/sdk/src/build/paths.ts";

const root = new URL("../", import.meta.url);
const at = (path: string): URL => new URL(path, root);

const PLUGIN_TEMPLATE_DIRECTORY = "applets/sdk/plugin/template/";
const PLUGIN_TEMPLATE_FILES = ["plugin.json", "plugin.ts"];
const PLUGIN_TEMPLATE_OUTPUT = "app/plugins/template.generated.ts";
/** Where the Plugins Skill is authored. */
export const PLUGIN_SKILL_SOURCE = at("app/plugins/skills/plugins/");
/** The Plugins Skill reference built from the SDK's own declarations. */
export const PLUGIN_TYPES_REFERENCE =
  "app/plugins/skills/plugins/references/types.md";
const PLUGIN_SKILL_OUTPUT = "app/skills/managed-plugins.generated.ts";
/** Where the Cards Skill is authored (ADR 0030). */
export const A2UI_SKILL_SOURCE = at("app/cards/skills/a2ui/");
const A2UI_SKILL_OUTPUT = "app/skills/managed-a2ui.generated.ts";
/** Recipe Skills authored as directories under the Skills Package. */
export const RECIPE_SKILL_SOURCE = at("app/skills/managed-skills/");
const RECIPE_SKILL_OUTPUT = "app/skills/managed-recipes.generated.ts";

async function prettyTypeScript(source: string): Promise<string> {
  return await format(source, { parser: "typescript" });
}

/**
 * Emitted into every generated module that carries text: the payloads travel
 * as base64 and are decoded once at load.
 *
 * Skill source contains `from "@frockbot/…"` inside string literals. Encoding keeps a text
 * scan over the compiled bundle honest, and keeps a generated module from
 * looking like it imports things it does not.
 */
const DECODE_HELPER = [
  "const TEXT_V1 = new TextDecoder();",
  "function fromBase64V1(value: string): string {",
  "  return TEXT_V1.decode(",
  "    Uint8Array.from(atob(value), (character) => character.charCodeAt(0)),",
  "  );",
  "}",
].join("\n");

function base64(text: string): string {
  return Buffer.from(text, "utf8").toString("base64");
}

/** The Plugin scaffold: strings, base64, decoded by `feature.ts`. */
async function pluginTemplateModule(): Promise<string> {
  const files: Array<{ path: string; base64: string }> = [];
  for (const path of PLUGIN_TEMPLATE_FILES) {
    const text = await Bun.file(
      at(`${PLUGIN_TEMPLATE_DIRECTORY}${path}`),
    ).text();
    files.push({ path, base64: base64(text) });
  }
  return await prettyTypeScript(
    [
      "// Generated by scripts/build-applets-assets.ts. Do not edit.",
      "//",
      "// The Plugin SDK's scaffold, as strings. `plugin_create` writes these",
      "// through the Workspace. Editing `applets/sdk/plugin/template/` and",
      "// rerunning the build is the only way to change what a new Plugin",
      "// starts as. The bodies are base64 so import specifiers in the scaffold",
      "// are not read as this module's own.",
      "export const PLUGIN_TEMPLATE_FILES_V1: ReadonlyArray<{",
      "  path: string;",
      "  base64: string;",
      `}> = ${JSON.stringify(files, null, 2)};`,
      "",
    ].join("\n"),
  );
}

/**
 * The Plugins Skill's `types.md`: the declarations `plugin_check` resolves
 * `@frockbot/applet-sdk/plugin` to, byte for byte. A Bot can read them nowhere
 * else — they are not on the Computer — so the Skill carries the very file the
 * checker uses, rebuilt from it here and proved fresh by `--check`.
 */
export async function pluginTypesReference(): Promise<string> {
  const declarations = await Bun.file(SDK_PLUGIN_TYPES).text();
  // Longer than any run of backticks inside, so the doc comments' own code
  // samples cannot close it.
  const fence = "`".repeat(
    Math.max(
      3,
      ...[...declarations.matchAll(/`+/g)].map((run) => run[0].length + 1),
    ),
  );
  return [
    "# Types",
    "",
    "Every type `@frockbot/applet-sdk/plugin` declares: the exact file `plugin_check` type-checks `plugin.ts` against, copied here whenever FrockBot is built.",
    "",
    'These declarations are not on the Computer. Nothing there can import or search for them, and an SDK you find there is not this one. Write `import type { … } from "@frockbot/applet-sdk/plugin"` and let `plugin_check` resolve it.',
    "",
    `${fence}ts`,
    declarations.trimEnd(),
    fence,
    "",
  ].join("\n");
}

/**
 * One authored Skill directory: its `SKILL.md` and the Markdown files under
 * `references/` (ADR 0030).
 *
 * The bounds are the loader's, checked here so a managed Skill that would be
 * refused at runtime fails the build instead.
 */
export async function skillDirectory(
  directory: URL,
): Promise<{ text: string; references: { path: string; text: string }[] }> {
  const text = await Bun.file(new URL("SKILL.md", directory)).text();
  if (text.length > SKILL_MAX_FILE_BYTES) {
    throw new Error(
      `${directory.pathname}SKILL.md is larger than ${SKILL_MAX_FILE_BYTES} bytes`,
    );
  }
  const referencesDirectory = new URL("references/", directory);
  // A Skill with nothing beside it is an ordinary Skill, not a broken one.
  const names = existsSync(referencesDirectory)
    ? readdirSync(referencesDirectory)
        .filter((name) => name.endsWith(".md"))
        .sort()
    : [];
  for (const name of names) {
    if (!isSkillReferenceNameV1(name)) {
      throw new Error(
        `${referencesDirectory.pathname}${name} is not a name the loader reads as a reference`,
      );
    }
  }
  if (names.length > SKILL_MAX_REFERENCES) {
    throw new Error(
      `${directory.pathname} offers ${names.length} references; the bound is ${SKILL_MAX_REFERENCES}`,
    );
  }
  const references: { path: string; text: string }[] = [];
  for (const path of names) {
    const body = await Bun.file(new URL(path, referencesDirectory)).text();
    if (new TextEncoder().encode(body).byteLength > SKILL_MAX_FILE_BYTES) {
      throw new Error(
        `${referencesDirectory.pathname}${path} is larger than ${SKILL_MAX_FILE_BYTES} bytes`,
      );
    }
    references.push({ path, text: body });
  }
  return { text, references };
}

function referencesLiteral(
  references: { path: string; text: string }[],
): string {
  return `[${references
    .map(
      (reference) =>
        `{ path: ${JSON.stringify(reference.path)}, text: fromBase64V1(${JSON.stringify(base64(reference.text))}) }`,
    )
    .join(", ")}]`;
}

const REFERENCES_TYPE = "ReadonlyArray<{ path: string; text: string }>";

/**
 * One authored Skill directory, as a managed Skill module.
 *
 * The Plugins Skill is authored in `app/plugins/skills/plugins/` and copied
 * into `app/skills`'s managed set — string constants compiled into that
 * Package, read-only because there is no path from `skill_write` to one.
 */
export async function managedSkillModule(source: {
  /** The constant prefix the module exports under, like `PLUGINS`. */
  prefix: string;
  slug: string;
  directory: URL;
  /** Where the Skill is authored, for the generated module's own comment. */
  authoredAt: string;
}): Promise<string> {
  const skill = await skillDirectory(source.directory);
  return await prettyTypeScript(
    [
      "// Generated by scripts/build-applets-assets.ts. Do not edit.",
      "//",
      `// Authored at ${source.authoredAt}.`,
      DECODE_HELPER,
      `export const ${source.prefix}_SKILL_SLUG_V1 = ${JSON.stringify(source.slug)};`,
      `export const ${source.prefix}_SKILL_DOCUMENT_V1 = fromBase64V1(${JSON.stringify(base64(skill.text))});`,
      `export const ${source.prefix}_SKILL_REFERENCES_V1: ${REFERENCES_TYPE} = ${referencesLiteral(skill.references)};`,
      "",
    ].join("\n"),
  );
}

const pluginSkillModule = (): Promise<string> =>
  managedSkillModule({
    prefix: "PLUGINS",
    slug: "plugins",
    directory: PLUGIN_SKILL_SOURCE,
    authoredAt: "app/plugins/skills/plugins/",
  });

/**
 * The Cards Skill, authored at `app/cards/skills/a2ui/`. Its `references/` are
 * generated from the two committed catalogs by
 * `scripts/generate-a2ui-skill.ts`, so a stale reference fails that check
 * before it reaches this one.
 */
const a2uiSkillModule = (): Promise<string> =>
  managedSkillModule({
    prefix: "A2UI",
    slug: "a2ui",
    directory: A2UI_SKILL_SOURCE,
    authoredAt: "app/cards/skills/a2ui/",
  });

async function recipeSkillsModule(): Promise<string> {
  const slugs = readdirSync(RECIPE_SKILL_SOURCE, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .sort();
  const skills: string[] = [];
  for (const slug of slugs) {
    const skill = await skillDirectory(
      new URL(`${slug}/`, RECIPE_SKILL_SOURCE),
    );
    skills.push(
      [
        "  {",
        `    slug: ${JSON.stringify(slug)},`,
        `    text: fromBase64V1(${JSON.stringify(base64(skill.text))}),`,
        `    references: ${referencesLiteral(skill.references)},`,
        "  }",
      ].join("\n"),
    );
  }
  return await prettyTypeScript(
    [
      "// Generated by scripts/build-applets-assets.ts. Do not edit.",
      "//",
      "// Authored at app/skills/managed-skills/<slug>/.",
      DECODE_HELPER,
      "export const MANAGED_RECIPE_SKILLS_V1: ReadonlyArray<{",
      "  slug: string;",
      "  text: string;",
      `  references: ${REFERENCES_TYPE};`,
      `}> = [${skills.join(",\n")}];`,
      "",
    ].join("\n"),
  );
}

// `types.md` comes before the Plugins Skill module, which reads it.
const outputs: Array<[string, () => Promise<string>]> = [
  [PLUGIN_TEMPLATE_OUTPUT, pluginTemplateModule],
  [PLUGIN_TYPES_REFERENCE, pluginTypesReference],
  [PLUGIN_SKILL_OUTPUT, pluginSkillModule],
  [A2UI_SKILL_OUTPUT, a2uiSkillModule],
  [RECIPE_SKILL_OUTPUT, recipeSkillsModule],
];

// Importing this module — the test drives `skillDirectory` directly — must not
// read or rewrite the checkout.
if (import.meta.main) {
  if (process.argv.includes("--check")) {
    for (const [path, build] of outputs) {
      const expected = await build();
      const current = await Bun.file(at(path))
        .text()
        .catch(() => "");
      if (current !== expected) {
        console.error(
          `${path} is stale; run \`bun scripts/build-applets-assets.ts\`.`,
        );
        process.exit(1);
      }
    }
    console.log("Managed Plugin assets are fresh.");
  } else {
    for (const [path, build] of outputs) {
      await Bun.write(at(path), await build());
    }
    console.log("Built the managed Plugin assets.");
  }
}
