// Turns three authored text files into TypeScript the Worker bundle can carry.
//
// The Applets feature is ordinary first-party code, but three of the things it
// ships are not TypeScript: the SDK scaffold a new Applet starts from, the
// Skill that teaches a Bot to write one, and the two HTML pages the shell
// serves into a sandboxed iframe. A Worker has no filesystem, so each has to
// reach the bundle as a string. That is all this script does.
//
// A Skill is a directory (ADR 0030), so each Skill source is read as one: its
// `SKILL.md` and whatever Markdown sits under `references/`, which travel as
// their own strings and are loaded on their own by `skill_load`.
//
// What it writes:
//
//   applets/template.generated.ts           the SDK scaffold
//   applets/pages.generated.ts              the two pages, with the bridge
//                                           helper inlined and each page's
//                                           digest
//   app/skills/managed-applets.generated.ts the Skill
//   app/plugins/template.generated.ts       the Plugin SDK scaffold (ADR 0026)
//   app/skills/managed-plugins.generated.ts the Plugins Skill
//   app/skills/managed-a2ui.generated.ts    the Cards Skill (ADR 0030), whose
//                                           references are themselves built by
//                                           scripts/generate-a2ui-skill.ts
//
// Freshness is proved by `--check`, which `bun run typecheck` runs.
import { existsSync, readdirSync } from "node:fs";
import { format } from "prettier";
import {
  SKILL_MAX_FILE_BYTES,
  SKILL_MAX_REFERENCES,
  isSkillReferenceNameV1,
} from "../app/skills/skill-md.ts";

const root = new URL("../", import.meta.url);
const at = (path: string): URL => new URL(path, root);

const TEMPLATE_DIRECTORY = "applets/sdk/template/";
// Written in this order by `applet_create`, so the newest file — the one the
// canvas opens on — is `server.ts`, the file a Bot edits first.
const TEMPLATE_FILES = ["README.md", "applet.json", "ui.tsx", "server.ts"];
const PAGE_IDS = ["list", "canvas"] as const;

const TEMPLATE_OUTPUT = "applets/template.generated.ts";
const PAGES_OUTPUT = "applets/pages.generated.ts";
/** Where the Applets Skill is authored, as the directory the generator reads. */
export const SKILL_SOURCE = at("applets/skills/applets/");
const SKILL_OUTPUT = "app/skills/managed-applets.generated.ts";
const PLUGIN_TEMPLATE_DIRECTORY = "applets/sdk/plugin/template/";
const PLUGIN_TEMPLATE_FILES = ["plugin.json", "plugin.ts"];
const PLUGIN_TEMPLATE_OUTPUT = "app/plugins/template.generated.ts";
/** Where the Plugins Skill is authored. */
export const PLUGIN_SKILL_SOURCE = at("app/plugins/skills/plugins/");
const PLUGIN_SKILL_OUTPUT = "app/skills/managed-plugins.generated.ts";
/** Where the Cards Skill is authored (ADR 0030). */
export const A2UI_SKILL_SOURCE = at("app/cards/skills/a2ui/");
const A2UI_SKILL_OUTPUT = "app/skills/managed-a2ui.generated.ts";

/** Content addressing, the same digest the page route verifies against. */
async function sha256Hex(text: string): Promise<string> {
  const digest = await crypto.subtle.digest(
    "SHA-256",
    new TextEncoder().encode(text),
  );
  return [...new Uint8Array(digest)]
    .map((byte) => byte.toString(16).padStart(2, "0"))
    .join("");
}

async function prettyTypeScript(source: string): Promise<string> {
  return await format(source, { parser: "typescript" });
}

/**
 * Emitted into every generated module that carries text: the payloads travel
 * as base64 and are decoded once at load.
 *
 * Applet source, the Skill that teaches it, and the pages that describe it all
 * contain `from "@frockbot/…"` inside string literals. Encoding keeps a text
 * scan over the compiled bundle honest, and keeps a generated module from
 * looking like it imports things it does not.
 */
const DECODE_HELPER = [
  "const TEXT_V1 = new TextDecoder();",
  "function fromBase64V1(value: string): string {",
  "  return TEXT_V1.decode(",
  "    Uint8Array.from(atob(value), (character) => character.charCodeAt(0)),",
  "  );",
  "}",
].join("\n");

function base64(text: string): string {
  return Buffer.from(text, "utf8").toString("base64");
}

async function templateModule(): Promise<string> {
  const files: Array<{ path: string; base64: string }> = [];
  for (const path of TEMPLATE_FILES) {
    const text = await Bun.file(at(`${TEMPLATE_DIRECTORY}${path}`)).text();
    files.push({ path, base64: base64(text) });
  }
  return await prettyTypeScript(
    [
      "// Generated by scripts/build-applets-assets.ts. Do not edit.",
      "//",
      "// The Applets SDK's scaffold, as strings. `applet_create` writes these",
      "// through the Workspace, and a Worker has no filesystem to read them",
      "// from, so the template travels in the bundle rather than beside it.",
      "// Editing `applets/sdk/template/` and rerunning the build is the only",
      "// way to change what a new Applet starts as.",
      "//",
      "// The bodies are base64 because Applet source contains import specifiers",
      "// that a text scan over the compiled bundle would otherwise read as this",
      "// module's own. `feature.ts` decodes them.",
      "export const APPLET_TEMPLATE_FILES_V1: ReadonlyArray<{",
      "  path: string;",
      "  base64: string;",
      `}> = ${JSON.stringify(files, null, 2)};`,
      "",
    ].join("\n"),
  );
}

/** The Plugin scaffold, the same way: strings, base64, decoded by `feature.ts`. */
async function pluginTemplateModule(): Promise<string> {
  const files: Array<{ path: string; base64: string }> = [];
  for (const path of PLUGIN_TEMPLATE_FILES) {
    const text = await Bun.file(
      at(`${PLUGIN_TEMPLATE_DIRECTORY}${path}`),
    ).text();
    files.push({ path, base64: base64(text) });
  }
  return await prettyTypeScript(
    [
      "// Generated by scripts/build-applets-assets.ts. Do not edit.",
      "//",
      "// The Plugin SDK's scaffold, as strings. `plugin_create` writes these",
      "// through the Workspace. Editing `applets/sdk/plugin/template/` and",
      "// rerunning the build is the only way to change what a new Plugin",
      "// starts as. Base64 for the same reason the Applet scaffold is.",
      "export const PLUGIN_TEMPLATE_FILES_V1: ReadonlyArray<{",
      "  path: string;",
      "  base64: string;",
      `}> = ${JSON.stringify(files, null, 2)};`,
      "",
    ].join("\n"),
  );
}

/** One page, with the versioned bridge helper substituted in. */
async function pageHtml(id: string, helper: string): Promise<string> {
  const source = await Bun.file(at(`applets/pages/${id}.html`)).text();
  // The placeholder is a bare identifier so the page stays valid HTML a
  // formatter can read; Prettier writes it back with a semicolon, so the
  // pattern tolerates one.
  const marker = /^[ \t]*PACKAGE_IFRAME_HELPER_JS_V1;?[ \t]*$/m;
  if (!marker.test(source)) {
    throw new Error(`page "${id}.html" has no bridge helper placeholder`);
  }
  return source.replace(marker, helper);
}

async function pagesModule(): Promise<string> {
  // Imported by path, not by specifier: this script runs from the repository
  // root, where the workspace's package names are not resolvable.
  const { PACKAGE_IFRAME_HELPER_JS_V1 } =
    await import("../core/contracts/iframe-ui.ts");
  const pages: Array<{
    id: string;
    contentHash: string;
    size: number;
    html: string;
  }> = [];
  for (const id of PAGE_IDS) {
    const html = await pageHtml(id, PACKAGE_IFRAME_HELPER_JS_V1);
    pages.push({
      id,
      contentHash: await sha256Hex(html),
      size: new TextEncoder().encode(html).byteLength,
      html,
    });
  }
  return await prettyTypeScript(
    [
      "// Generated by scripts/build-applets-assets.ts. Do not edit.",
      "//",
      "// The Applets Package's two pages, authored at `applets/pages/`, with",
      "// the versioned iframe bridge helper substituted for its placeholder.",
      "// `pages.ts` names the tools each page may call and the slots it mounts",
      "// into.",
      "//",
      "// The digest is what the anonymous page origin serves the bytes under and",
      "// re-verifies before answering, so a page is addressed by its content the",
      "// way a Bot-authored one is.",
      DECODE_HELPER,
      "",
      "export const APPLETS_PAGE_SOURCES_V1: ReadonlyArray<{",
      "  pageId: string;",
      "  contentHash: string;",
      "  size: number;",
      "  html: string;",
      "}> = [",
      ...pages.map(
        (page) =>
          `  { pageId: ${JSON.stringify(page.id)}, contentHash: ${JSON.stringify(
            page.contentHash,
          )}, size: ${page.size}, html: fromBase64V1(${JSON.stringify(
            base64(page.html),
          )}) },`,
      ),
      "];",
      "",
    ].join("\n"),
  );
}

/**
 * One authored Skill directory: its `SKILL.md` and the Markdown files under
 * `references/` (ADR 0030).
 *
 * The bounds are the loader's, checked here so a managed Skill that would be
 * refused at runtime fails the build instead.
 */
export async function skillDirectory(
  directory: URL,
): Promise<{ text: string; references: { path: string; text: string }[] }> {
  const text = await Bun.file(new URL("SKILL.md", directory)).text();
  if (text.length > SKILL_MAX_FILE_BYTES) {
    throw new Error(
      `${directory.pathname}SKILL.md is larger than ${SKILL_MAX_FILE_BYTES} bytes`,
    );
  }
  const referencesDirectory = new URL("references/", directory);
  // A Skill with nothing beside it is an ordinary Skill, not a broken one.
  const names = existsSync(referencesDirectory)
    ? readdirSync(referencesDirectory)
        .filter((name) => name.endsWith(".md"))
        .sort()
    : [];
  for (const name of names) {
    if (!isSkillReferenceNameV1(name)) {
      throw new Error(
        `${referencesDirectory.pathname}${name} is not a name the loader reads as a reference`,
      );
    }
  }
  if (names.length > SKILL_MAX_REFERENCES) {
    throw new Error(
      `${directory.pathname} offers ${names.length} references; the bound is ${SKILL_MAX_REFERENCES}`,
    );
  }
  const references: { path: string; text: string }[] = [];
  for (const path of names) {
    const body = await Bun.file(new URL(path, referencesDirectory)).text();
    if (new TextEncoder().encode(body).byteLength > SKILL_MAX_FILE_BYTES) {
      throw new Error(
        `${referencesDirectory.pathname}${path} is larger than ${SKILL_MAX_FILE_BYTES} bytes`,
      );
    }
    references.push({ path, text: body });
  }
  return { text, references };
}

function referencesLiteral(
  references: { path: string; text: string }[],
): string {
  return `[${references
    .map(
      (reference) =>
        `{ path: ${JSON.stringify(reference.path)}, text: fromBase64V1(${JSON.stringify(base64(reference.text))}) }`,
    )
    .join(", ")}]`;
}

const REFERENCES_TYPE = "ReadonlyArray<{ path: string; text: string }>";

/**
 * One authored Skill directory, as a managed Skill module.
 *
 * The Applets Skill is authored in `applets/skills/applets/`, beside the
 * feature it documents, and copied into `app/skills`'s managed set — string
 * constants compiled into that Package, read-only because there is no path
 * from `skill_write` to one. The Plugins Skill is the same, from its own
 * directory, so both go through here.
 */
export async function managedSkillModule(source: {
  /** The constant prefix the module exports under, like `APPLETS`. */
  prefix: string;
  slug: string;
  directory: URL;
  /** Where the Skill is authored, for the generated module's own comment. */
  authoredAt: string;
}): Promise<string> {
  const skill = await skillDirectory(source.directory);
  return await prettyTypeScript(
    [
      "// Generated by scripts/build-applets-assets.ts. Do not edit.",
      "//",
      `// Authored at ${source.authoredAt}.`,
      DECODE_HELPER,
      `export const ${source.prefix}_SKILL_SLUG_V1 = ${JSON.stringify(source.slug)};`,
      `export const ${source.prefix}_SKILL_DOCUMENT_V1 = fromBase64V1(${JSON.stringify(base64(skill.text))});`,
      `export const ${source.prefix}_SKILL_REFERENCES_V1: ${REFERENCES_TYPE} = ${referencesLiteral(skill.references)};`,
      "",
    ].join("\n"),
  );
}

const skillModule = (): Promise<string> =>
  managedSkillModule({
    prefix: "APPLETS",
    slug: "applets",
    directory: SKILL_SOURCE,
    authoredAt: "applets/skills/applets/",
  });

/** The Plugins Skill, authored at `app/plugins/skills/plugins/`. */
const pluginSkillModule = (): Promise<string> =>
  managedSkillModule({
    prefix: "PLUGINS",
    slug: "plugins",
    directory: PLUGIN_SKILL_SOURCE,
    authoredAt: "app/plugins/skills/plugins/",
  });

/**
 * The Cards Skill, authored at `app/cards/skills/a2ui/`. Its `references/` are
 * generated from the two committed catalogs by
 * `scripts/generate-a2ui-skill.ts`, so a stale reference fails that check
 * before it reaches this one.
 */
const a2uiSkillModule = (): Promise<string> =>
  managedSkillModule({
    prefix: "A2UI",
    slug: "a2ui",
    directory: A2UI_SKILL_SOURCE,
    authoredAt: "app/cards/skills/a2ui/",
  });

const outputs: Array<[string, () => Promise<string>]> = [
  [TEMPLATE_OUTPUT, templateModule],
  [PAGES_OUTPUT, pagesModule],
  [SKILL_OUTPUT, skillModule],
  [PLUGIN_TEMPLATE_OUTPUT, pluginTemplateModule],
  [PLUGIN_SKILL_OUTPUT, pluginSkillModule],
  [A2UI_SKILL_OUTPUT, a2uiSkillModule],
];

// Importing this module — the test drives `skillDirectory` directly — must not
// read or rewrite the checkout.
if (import.meta.main) {
  if (process.argv.includes("--check")) {
    for (const [path, build] of outputs) {
      const expected = await build();
      const current = await Bun.file(at(path))
        .text()
        .catch(() => "");
      if (current !== expected) {
        console.error(
          `${path} is stale; run \`bun scripts/build-applets-assets.ts\`.`,
        );
        process.exit(1);
      }
    }
    console.log("Applets assets are fresh.");
  } else {
    for (const [path, build] of outputs) {
      await Bun.write(at(path), await build());
    }
    console.log("Built the Applets assets.");
  }
}
