// Bundles what `plugin_module_try` runs on a Bot's Computer (ADR 0037) into
// the Worker, which has no filesystem to read it from:
//
//   core/contracts/plugin-module-try.generated.ts
//     the module runtime the Mac runs every module through, and the try's
//     runner, both from `apps/device-host` with the Mac build's options.
//
// Freshness is proved by `--check`, which `bun run typecheck` runs.

import { build } from "esbuild";
import { format } from "prettier";

import { DEVICE_HOST_BUILD_OPTIONS_V1 } from "../apps/device-host/build.ts";

const root = new URL("../", import.meta.url);
const OUTPUT = "core/contracts/plugin-module-try.generated.ts";

async function bundled(): Promise<{ runtime: string; runner: string }> {
  const result = await build({
    ...DEVICE_HOST_BUILD_OPTIONS_V1,
    // Relative to the repository, so the paths esbuild writes into its
    // comments are the same on every machine.
    absWorkingDir: root.pathname,
    entryPoints: {
      "device-runtime": "apps/device-host/src/runtime.ts",
      "module-try": "apps/device-host/src/try-main.ts",
    },
    outdir: "out",
    write: false,
  });
  const text = (name: string): string => {
    const file = result.outputFiles.find((output) =>
      output.path.endsWith(`/${name}.js`),
    );
    if (!file) throw new Error(`esbuild wrote no ${name}.js`);
    return file.text;
  };
  return { runtime: text("device-runtime"), runner: text("module-try") };
}

function base64(text: string): string {
  return Buffer.from(text, "utf8").toString("base64");
}

async function generated(): Promise<string> {
  const { runtime, runner } = await bundled();
  return await format(
    [
      "// Generated by scripts/build-module-try.ts. Do not edit.",
      "//",
      "// What `plugin_module_try` runs on the Bot's Computer, bundled from",
      "// `apps/device-host`. Base64, because the tool hands each one to the",
      "// Computer that way and a text scan of the Worker bundle should not",
      "// read them as its own code.",
      "",
      "/** `device-runtime.js`: the entry every module's process runs. */",
      `export const PLUGIN_MODULE_RUNTIME_JS_BASE64_V1 = ${JSON.stringify(base64(runtime))};`,
      "",
      "/** `module-try.js`: the try's runner, as Node runs it. */",
      `export const PLUGIN_MODULE_TRY_RUNNER_JS_BASE64_V1 = ${JSON.stringify(base64(runner))};`,
      "",
    ].join("\n"),
    { parser: "typescript" },
  );
}

const expected = await generated();
const target = new URL(OUTPUT, root);
if (process.argv.includes("--check")) {
  const file = Bun.file(target);
  const current = (await file.exists()) ? await file.text() : "";
  if (current !== expected) {
    console.error(`${OUTPUT} is stale. Run: bun scripts/build-module-try.ts`);
    process.exit(1);
  }
} else {
  await Bun.write(target, expected);
  console.log(`wrote ${OUTPUT}`);
}
