import { readFileSync } from "node:fs";
import { source, root, output, type Schema } from "./protocol-codegen.ts";
import { resolve } from "node:path";

// Keep the Dart evaluator's dialect explicit. Growing the schema requires
// adding semantics here and shared negative fixtures, never silently ignoring.
const keywords = new Set([
  "allOf",
  "if",
  "then",
  "$ref",
  "type",
  "const",
  "enum",
  "oneOf",
  "properties",
  "required",
  "additionalProperties",
  "items",
  "minLength",
  "maxLength",
  "pattern",
  "minimum",
  "maximum",
  "minItems",
  "maxItems",
  "uniqueItems",
  "maxProperties",
  "propertyNames",
]);
function check(s: Schema): void {
  for (const key of Object.keys(s))
    if (!keywords.has(key))
      throw new Error(`Dart generator does not support ${key}`);
  for (const child of Object.values(s.properties ?? {})) check(child);
  for (const child of s.oneOf ?? []) check(child);
  for (const child of (s.allOf as Schema[] | undefined) ?? []) check(child);
  for (const key of ["if", "then"] as const)
    if (s[key]) check(s[key] as Schema);
  for (const key of [
    "items",
    "additionalProperties",
    "propertyNames",
  ] as const) {
    if (s[key] && typeof s[key] === "object") check(s[key] as Schema);
  }
  if (s.$ref && !Object.hasOwn(source.$defs, s.$ref.replace("#/$defs/", "")))
    throw new Error("Only local named refs are supported");
}
Object.values(source.$defs).forEach(check);
const literal = (value: unknown) =>
  JSON.stringify(JSON.stringify(value)).replaceAll("$", "\\$");
const names = Object.keys(source.$defs);
const runtime = readFileSync(
  resolve(root, "scripts/protocol-dart-runtime.txt"),
  "utf8",
);
const compatibility = JSON.stringify({
  schemaVersion: 1,
  ...source["x-frockbot-compatibility"],
}).replaceAll("$", "\\$");
function dartType(s: Schema): string {
  if (s.$ref) return s.$ref.split("/").at(-1)!;
  const values = s.enum ?? ("const" in s ? [s.const] : undefined);
  if (values?.every((v) => typeof v === "string")) return "String";
  if (values?.every((v) => typeof v === "boolean")) return "bool";
  if (values?.every((v) => typeof v === "number" && Number.isInteger(v)))
    return "int";
  switch (s.type) {
    case "string":
      return "String";
    case "boolean":
      return "bool";
    case "integer":
      return "int";
    case "number":
      return "num";
    case "object":
      return "Map<String, Object?>";
    case "array":
      return `List<${dartType(s.items!)}>`;
    default:
      return "Object?";
  }
}
function dartValue(s: Schema, value: string): string {
  if (s.$ref) return `${dartType(s)}.fromJson(${value})`;
  if (s.type === "array")
    return `List<${dartType(s.items!)}>.unmodifiable((${value} as List).map((item) => ${dartValue(s.items!, "item")}))`;
  const type = dartType(s);
  if (type === "Map<String, Object?>")
    return `Map<String, Object?>.unmodifiable(${value} as Map)`;
  if (type === "int") return `(${value} as num).toInt()`;
  return type === "Object?" ? value : `(${value} as ${type})`;
}
function fields(s: Schema): string {
  if (!s.properties)
    return `  ${dartType(s)} get value => ${dartValue(s, "toJson()")};`;
  return Object.entries(s.properties ?? {})
    .map(([key, field]) => {
      // Source property names are identifiers. Refuse future names that need a
      // Dart naming policy instead of emitting invalid source or collisions.
      if (
        !/^[a-zA-Z][a-zA-Z0-9]*$/.test(key) ||
        ["toJson", "fromJson", "_json"].includes(key)
      )
        throw new Error(`Unsupported Dart field name ${key}`);
      const required = s.required?.includes(key);
      const type = dartType(field);
      const value = dartValue(
        field,
        `jsonDecode(jsonEncode(${required ? "(_json as Map)" : "_json"}['${key}']))`,
      );
      return `  ${type}${required || type.endsWith("?") ? "" : "?"} get ${key} => ${required ? value : `(_json as Map).containsKey('${key}') ? ${value} : null`};`;
    })
    .join("\n");
}
const code = `// Generated by bun scripts/generate-dart-protocol.ts. Do not edit.\nimport 'dart:convert';\n\nfinal Map<String, dynamic> _definitions = jsonDecode(${literal(source.$defs)}) as Map<String, dynamic>;\nconst clientCompatibility = ${compatibility};\nconst supportedProtocolMin = ${source["x-frockbot-compatibility"].protocolMin};\nconst supportedProtocolMax = ${source["x-frockbot-compatibility"].protocolMax};\nconst minimumNativeVersion = '${source["x-frockbot-compatibility"].minimumNativeVersion}';\n\n${runtime}\n${names.map((n) => `/// Validated ${n}; JSON unions retain their discriminator in toJson().\nclass ${n} {\n  final Object? _json;\n  ${n}.fromJson(Object? value) : _json = decodeProtocol('${n}', value);\n  Object? toJson() => jsonDecode(jsonEncode(_json));\n${fields(source.$defs[n]!)}\n}\n`).join("\n")}`;
await output("apps/native/lib/protocol/client_wire.generated.dart", code);
