import ts from "typescript";
import { format } from "prettier";

const interfaceNames = [
  "BotPackageContextV1",
  "BotPackageExecutionContextV1",
  "BotPackageHookContextV1",
] as const;
const sourcePath = new URL(
  "../packages/kernel-contracts/src/isolate.ts",
  import.meta.url,
);
const outputPath = new URL(
  "../packages/kernel-contracts/src/isolate-context-catalog.generated.ts",
  import.meta.url,
);

function generatedSource(sourceText: string): string {
  const source = ts.createSourceFile(
    sourcePath.pathname,
    sourceText,
    ts.ScriptTarget.Latest,
    true,
    ts.ScriptKind.TS,
  );
  const declarations = interfaceNames.map((interfaceName) =>
    source.statements.find(
      (statement): statement is ts.InterfaceDeclaration =>
        ts.isInterfaceDeclaration(statement) &&
        statement.name.text === interfaceName,
    ),
  );
  const missing = interfaceNames.find((_name, index) => !declarations[index]);
  if (missing) throw new Error(`missing ${missing} in isolate.ts`);
  const [context, execution, hook] = declarations as [
    ts.InterfaceDeclaration,
    ts.InterfaceDeclaration,
    ts.InterfaceDeclaration,
  ];

  const printer = ts.createPrinter({ newLine: ts.NewLineKind.LineFeed });
  const dts = [context, execution, hook]
    .map((declaration) =>
      printer
        .printNode(ts.EmitHint.Unspecified, declaration, source)
        .replace("export interface", "interface"),
    )
    .join("\n\n");
  const keys = context.members.map((member) => {
    const name = member.name;
    if (!name || (!ts.isIdentifier(name) && !ts.isStringLiteral(name))) {
      throw new Error(
        `BotPackageContextV1 contains an unsupported member name`,
      );
    }
    return name.text;
  });
  const commonSummary = context.members
    .map((member) =>
      printer
        .printNode(ts.EmitHint.Unspecified, member, source)
        .replace(/\s+/g, " ")
        .trim(),
    )
    .join(" ");

  return (
    `// Generated by scripts/generate-isolate-context-catalog.ts. Do not edit.\n` +
    `export const BOT_ISOLATE_CONTEXT_DTS_V1 = ${JSON.stringify(dts)};\n` +
    `export const BOT_ISOLATE_CONTEXT_KEYS_V1 = ${JSON.stringify(keys)} as const;\n` +
    `export const BOT_ISOLATE_CONTEXT_SUMMARY_V1 = ${JSON.stringify(`Package execute and hook ctx share: ${commonSummary}`)};\n`
  );
}

const expected = await format(
  generatedSource(await Bun.file(sourcePath).text()),
  { parser: "typescript" },
);
if (process.argv.includes("--check")) {
  const current = await Bun.file(outputPath)
    .text()
    .catch(() => "");
  if (current !== expected) {
    console.error(
      "Bot isolate context catalog is stale; run `bun scripts/generate-isolate-context-catalog.ts`.",
    );
    process.exit(1);
  }
  console.log("Bot isolate context catalog is fresh.");
} else {
  await Bun.write(outputPath, expected);
  console.log("Generated Bot isolate context catalog.");
}
