// The JSON Schema draft 2020-12 documents, compiled into the card renderer.
//
// A Card is drawn from JSON Schema (ADR 0030), and the schema stack the
// renderer uses resolves whatever a schema names: the A2UI common types it
// registers declare `$schema: https://json-schema.org/draft/2020-12/schema`,
// so validation reaches for the draft's meta-schema and the vocabulary
// meta-schemas it refers to. Those are documents, not services: fetching them
// from json-schema.org is a request the deployment's CSP refuses and the
// product never needs, because the same documents already ship with this
// repository's own validator.
//
// So they are lifted from ajv — the deployment's JSON Schema 2020-12
// implementation, a root dependency, whose delivered `refs/json-schema-2020-12`
// is the published set — keyed by each document's canonical `$id`, and written
// as Dart source `apps/native/packages/frockbot_client/lib/cards/schema_documents.g.dart`. The client
// answers those URIs from this build and refuses every other URI, so a card
// never leaves the app to be validated, and the two implementations of the
// draft here (ajv in a Worker, this client) read the same words.
//
// `--check` is what `bun run typecheck` runs: an ajv bump that moved these
// documents stops the build rather than shipping a client whose metaschema
// disagrees with its validator's.
import { existsSync, readdirSync, readFileSync } from "node:fs";
import { format } from "prettier";

const root = new URL("../", import.meta.url);
const at = (path: string): URL => new URL(path, root);

const AJV_REFS = "node_modules/ajv/dist/refs/json-schema-2020-12";
const OUTPUT =
  "apps/native/packages/frockbot_client/lib/cards/schema_documents.g.dart";

/** One document: its canonical `$id`, and its exact text. */
interface Document {
  id: string;
  text: string;
}

async function readDocument(path: URL): Promise<Document> {
  const text = readFileSync(path, "utf8");
  const parsed = JSON.parse(text) as { $id?: unknown };
  if (typeof parsed.$id !== "string" || parsed.$id.length === 0) {
    throw new Error(`${path.pathname} has no $id`);
  }
  // A raw Dart string is what carries the JSON verbatim, so the one sequence
  // that could end one early is refused rather than escaped.
  if (text.includes("'''")) {
    throw new Error(`${path.pathname} contains a triple quote`);
  }
  return {
    id: parsed.$id,
    text: (await format(text, { parser: "json" })).trimEnd(),
  };
}

async function documents(): Promise<Document[]> {
  const files = [
    at(`${AJV_REFS}/schema.json`),
    ...readdirSync(at(`${AJV_REFS}/meta`))
      .filter((name) => name.endsWith(".json"))
      .sort()
      .map((name) => at(`${AJV_REFS}/meta/${name}`)),
  ];
  const read = await Promise.all(files.map(readDocument));
  return read.sort((left, right) => left.id.localeCompare(right.id));
}

function generatedSource(entries: readonly Document[]): string {
  const map = entries
    .map((entry) => `  ${JSON.stringify(entry.id)}: r'''\n${entry.text}\n''',`)
    .join("\n");
  const provenance = entries
    .map((entry) => `///  * \`${entry.id}\``)
    .join("\n");
  return (
    "// Generated by scripts/generate-card-schema-documents.ts. Do not edit.\n" +
    "//\n" +
    "// The JSON Schema draft 2020-12 meta-schema and the vocabulary\n" +
    "// meta-schemas it refers to, exactly as ajv (the validator this\n" +
    "// repository already ships) delivers them, by canonical `$id`:\n" +
    "//\n" +
    `${provenance}\n` +
    "library;\n\n" +
    "/// The draft 2020-12 documents this build answers schema resolution from,\n" +
    "/// so drawing a Card reaches no network.\n" +
    "const Map<String, String> cardSchemaDocumentsV1 = <String, String>{\n" +
    `${map}\n` +
    "};\n"
  );
}

const expected = generatedSource(await documents());
if (process.argv.includes("--check")) {
  const outputPath = at(OUTPUT);
  const current = existsSync(outputPath)
    ? readFileSync(outputPath, "utf8")
    : "";
  if (current !== expected) {
    console.error(
      "Card schema documents are stale; run `bun scripts/generate-card-schema-documents.ts`.",
    );
    process.exit(1);
  }
  console.log("Card schema documents are fresh.");
} else {
  await Bun.write(at(OUTPUT), expected);
  console.log("Generated the card schema documents.");
}
