import ts from "typescript";
import { format } from "prettier";

const interfaceName = "BotPackageExecutionContextV1";
const sourcePath = new URL(
  "../packages/kernel-contracts/src/isolate.ts",
  import.meta.url,
);
const outputPath = new URL(
  "../packages/kernel-contracts/src/isolate-context-catalog.generated.ts",
  import.meta.url,
);

function generatedSource(sourceText: string): string {
  const source = ts.createSourceFile(
    sourcePath.pathname,
    sourceText,
    ts.ScriptTarget.Latest,
    true,
    ts.ScriptKind.TS,
  );
  const declaration = source.statements.find(
    (statement): statement is ts.InterfaceDeclaration =>
      ts.isInterfaceDeclaration(statement) &&
      statement.name.text === interfaceName,
  );
  if (!declaration) throw new Error(`missing ${interfaceName} in isolate.ts`);

  const printer = ts.createPrinter({ newLine: ts.NewLineKind.LineFeed });
  const dts = printer
    .printNode(ts.EmitHint.Unspecified, declaration, source)
    .replace("export interface", "interface");
  const keys = declaration.members.map((member) => {
    const name = member.name;
    if (!name || (!ts.isIdentifier(name) && !ts.isStringLiteral(name))) {
      throw new Error(`${interfaceName} contains an unsupported member name`);
    }
    return name.text;
  });
  const summary = declaration.members
    .map((member) =>
      printer
        .printNode(ts.EmitHint.Unspecified, member, source)
        .replace(/\s+/g, " ")
        .trim(),
    )
    .join(" ");

  return (
    `// Generated by scripts/generate-isolate-context-catalog.ts. Do not edit.\n` +
    `export const BOT_ISOLATE_CONTEXT_DTS_V1 = ${JSON.stringify(dts)};\n` +
    `export const BOT_ISOLATE_CONTEXT_KEYS_V1 = ${JSON.stringify(keys)} as const;\n` +
    `export const BOT_ISOLATE_CONTEXT_SUMMARY_V1 = ${JSON.stringify(`Package execute ctx: ${summary}`)};\n`
  );
}

const expected = await format(
  generatedSource(await Bun.file(sourcePath).text()),
  { parser: "typescript" },
);
if (process.argv.includes("--check")) {
  const current = await Bun.file(outputPath)
    .text()
    .catch(() => "");
  if (current !== expected) {
    console.error(
      "Bot isolate context catalog is stale; run `bun scripts/generate-isolate-context-catalog.ts`.",
    );
    process.exit(1);
  }
  console.log("Bot isolate context catalog is fresh.");
} else {
  await Bun.write(outputPath, expected);
  console.log("Generated Bot isolate context catalog.");
}
