import { readFileSync } from "node:fs";
import { source, root, output, type Schema } from "./protocol-codegen.ts";
import { resolve } from "node:path";

// Keep the Dart evaluator's dialect explicit. Growing the schema requires
// adding semantics here and shared negative fixtures, never silently ignoring.
const keywords = new Set([
  "allOf",
  "if",
  "then",
  "$ref",
  "type",
  "const",
  "enum",
  "oneOf",
  "properties",
  "required",
  "additionalProperties",
  "items",
  "minLength",
  "maxLength",
  "pattern",
  "minimum",
  "maximum",
  "minItems",
  "maxItems",
  "uniqueItems",
  "maxProperties",
  "propertyNames",
]);
function check(s: Schema): void {
  for (const key of Object.keys(s))
    if (!keywords.has(key))
      throw new Error(`Dart generator does not support ${key}`);
  for (const child of Object.values(s.properties ?? {})) check(child);
  for (const child of s.oneOf ?? []) check(child);
  for (const child of (s.allOf as Schema[] | undefined) ?? []) check(child);
  for (const key of ["if", "then"] as const)
    if (s[key]) check(s[key] as Schema);
  for (const key of [
    "items",
    "additionalProperties",
    "propertyNames",
  ] as const) {
    if (s[key] && typeof s[key] === "object") check(s[key] as Schema);
  }
  if (s.$ref && !Object.hasOwn(source.$defs, s.$ref.replace("#/$defs/", "")))
    throw new Error("Only local named refs are supported");
}
Object.values(source.$defs).forEach(check);
const literal = (value: unknown) =>
  JSON.stringify(JSON.stringify(value)).replaceAll("$", "\\$");
const names = Object.keys(source.$defs);
const runtime = readFileSync(
  resolve(root, "scripts/protocol-dart-runtime.txt"),
  "utf8",
);
const compatibility = JSON.stringify({
  schemaVersion: 1,
  ...source["x-frockbot-compatibility"],
}).replaceAll("$", "\\$");
const code = `// Generated by bun scripts/generate-dart-protocol.ts. Do not edit.\nimport 'dart:convert';\n\nfinal Map<String, dynamic> _definitions = jsonDecode(${literal(source.$defs)}) as Map<String, dynamic>;\nconst clientCompatibility = ${compatibility};\nconst supportedProtocolMin = ${source["x-frockbot-compatibility"].protocolMin};\nconst supportedProtocolMax = ${source["x-frockbot-compatibility"].protocolMax};\nconst minimumNativeVersion = '${source["x-frockbot-compatibility"].minimumNativeVersion}';\n\n${runtime}\n${names.map((n) => `/// A decoded ${n}; typed native presentation models are added with their slice.\nclass ${n} {\n  final Object? _json;\n  ${n}.fromJson(Object? value) : _json = decodeProtocol('${n}', value);\n  Object? toJson() => jsonDecode(jsonEncode(_json));\n}\n`).join("\n")}`;
await output("apps/native/lib/protocol/client_wire.generated.dart", code);
