#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold)
  DIM=$(tput dim)
  RESET=$(tput sgr0)
  BLUE=$(tput setaf 4)
  GREEN=$(tput setaf 2)
  YELLOW=$(tput setaf 3)
else
  BOLD=""
  DIM=""
  RESET=""
  BLUE=""
  GREEN=""
  YELLOW=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say() { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  {
    if command -v wslview >/dev/null 2>&1; then
      wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then
      explorer.exe "$url"
    elif command -v xdg-open >/dev/null 2>&1; then
      xdg-open "$url"
    elif command -v open >/dev/null 2>&1; then
      open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line
  line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" >"$tmp" || true
  printf '%s=%s\n' "$key" "$value" >>"$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  ((${#WRITTEN_ENV[@]})) && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  ((${#WRITTEN_SECRET[@]})) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if ((${#SKIPPED[@]})); then
    printf '\n'
    warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

GITHUB_REPOSITORY="timoconnellaus/frockbot"
GITHUB_ENVIRONMENT="production"

set_production_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" \
      --repo "$GITHUB_REPOSITORY" \
      --env "$GITHUB_ENVIRONMENT" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub production secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub production secret $name")
  warn "could not set $name; authenticate gh and rerun this wizard"
}

set_required_production_secret() {
  local name="$1" value="$2"
  if ! printf '%s' "$value" | gh secret set "$name" \
    --repo "$GITHUB_REPOSITORY" \
    --env "$GITHUB_ENVIRONMENT" >/dev/null 2>&1; then
    warn "could not set required production secret $name"
    return 1
  fi
  WRITTEN_SECRET+=("$name")
  printf '  %s✓ set%s required GitHub production secret %s\n' "$GREEN" "$RESET" "$name"
}

banner "FrockBot production setup"

stage "Cloudflare: CI deployment token"
say "Create the least-privilege token Wrangler uses from GitHub Actions."
open_url "https://dash.cloudflare.com/?to=/:account/api-tokens"
step "Select Create Token, then choose the Custom → Edit Cloudflare Workers policy."
step "Add Account permissions D1 Write and Workers R2 Storage Write."
step "Scope account resources to Tim.oconnell.australia@gmail.com's Account only."
step "Scope zone resources to frockbot.com only, then create and copy the token."
ask_secret CLOUDFLARE_API_TOKEN "Paste the Cloudflare API token:"
[[ -n "$CLOUDFLARE_API_TOKEN" ]] || {
  warn "A token is required"
  exit 1
}
set_production_secret CLOUDFLARE_API_TOKEN "$CLOUDFLARE_API_TOKEN"

stage "Cloudflare: Package Catalog bucket"
say "Provision the R2 bucket that holds the remote Package Catalog."
note "CI creates this bucket on every deploy too, so this stage is a no-op once deployed."
CATALOG_BUCKET="frockbot-package-catalog"
CATALOG_CONFIG="apps/cloudflare/wrangler.jsonc"
if CLOUDFLARE_API_TOKEN="$CLOUDFLARE_API_TOKEN" \
  bunx wrangler r2 bucket info "$CATALOG_BUCKET" --config "$CATALOG_CONFIG" >/dev/null 2>&1; then
  note "$CATALOG_BUCKET already exists."
elif CLOUDFLARE_API_TOKEN="$CLOUDFLARE_API_TOKEN" \
  bunx wrangler r2 bucket create "$CATALOG_BUCKET" --config "$CATALOG_CONFIG" >/dev/null 2>&1; then
  printf '  %s✓ created%s R2 bucket %s\n' "$GREEN" "$RESET" "$CATALOG_BUCKET"
else
  SKIPPED+=("R2 bucket $CATALOG_BUCKET (run this wizard from the repository root, or let CI create it)")
  warn "could not create $CATALOG_BUCKET here; CI creates it on the next deploy"
fi

stage "Google: OAuth branding and web client"
say "Configure the Google identity used by bot.frockbot.com."
open_url "https://console.developers.google.com/auth/branding"
step "Select or create the production Google Cloud project."
step "Set the app name to FrockBot, choose your support email, and save the branding form."
step "If Google asks for an audience, choose External and publish it when ready for non-test users."
pause "Press Enter after the branding and audience are configured."
open_url "https://console.developers.google.com/auth/clients"
step "Select Create client and choose Web application. Name it FrockBot production."
step "Add Authorized JavaScript origin: https://bot.frockbot.com"
step "Add Authorized redirect URI: https://bot.frockbot.com/api/auth/callback/google"
step "Create the client, then copy its client ID and client secret."
ask GOOGLE_CLIENT_ID "Paste the Google client ID:"
ask_secret GOOGLE_CLIENT_SECRET "Paste the Google client secret:"
[[ -n "$GOOGLE_CLIENT_ID" && -n "$GOOGLE_CLIENT_SECRET" ]] || {
  warn "Both Google OAuth values are required"
  exit 1
}
set_production_secret GOOGLE_CLIENT_ID "$GOOGLE_CLIENT_ID"
set_production_secret GOOGLE_CLIENT_SECRET "$GOOGLE_CLIENT_SECRET"

stage "Fly: Sprites Computer token"
say "Provision the server-side credential used by the built-in Fly Computer provider."
open_url "https://fly.io/dashboard"
step "Open the organization that owns FrockBot Sprites and create a scoped Sprites access token."
step "Copy the token. It remains a GitHub production secret and is never sent to clients."
ask_secret SPRITES_TOKEN "Paste the Fly Sprites token:"
[[ -n "$SPRITES_TOKEN" ]] || {
  warn "A Fly Sprites token is required"
  exit 1
}
set_production_secret SPRITES_TOKEN "$SPRITES_TOKEN"

stage "Cloudflare: AI Gateway authorization token"
say "Provision the bearer the Worker presents to the AI Gateway named by FROCK_AI_GATEWAY_ID."
say "Frock AI Auto resolves to a dynamic route, and a dynamic route is only accepted on the"
say "Gateway's compat endpoint (cloudflare/ai#617). Reaching that endpoint needs this token."
open_url "https://dash.cloudflare.com/?to=/:account/ai/ai-gateway"
step "Open the 'flock' Gateway, turn on Authenticated Gateway, and create a token."
step "Leave this blank to skip: Auto then fails and only manual @frock/ models work."
ask_secret FROCK_AI_GATEWAY_TOKEN "Paste the AI Gateway authorization token (optional):"
if [[ -n "$FROCK_AI_GATEWAY_TOKEN" ]]; then
  set_production_secret FROCK_AI_GATEWAY_TOKEN "$FROCK_AI_GATEWAY_TOKEN"
else
  note "No AI Gateway token set; Frock AI Auto will not work until one is provided."
fi

stage "FrockBot: per-account credential encryption"
say "Provision the versioned backend keyring that encrypts Connection credentials at rest."
if ! command -v gh >/dev/null 2>&1 || ! gh auth status >/dev/null 2>&1; then
  warn "GitHub CLI authentication is required to inspect the production keyring"
  exit 1
fi
if ! PRODUCTION_SECRETS="$(
  gh secret list --repo "$GITHUB_REPOSITORY" --env "$GITHUB_ENVIRONMENT"
)"; then
  warn "Could not inspect production secrets; preserving the existing keyring requires a successful inspection"
  exit 1
fi
if awk '{print $1}' <<<"$PRODUCTION_SECRETS" | grep -qx CREDENTIAL_KEYRING; then
  note "Preserving the existing CREDENTIAL_KEYRING so stored credentials remain decryptable."
else
  CREDENTIAL_KEYRING="$({
    node <<'NODE'
const { randomBytes } = require('node:crypto');
const keyId = new Date().toISOString().slice(0, 7);
process.stdout.write(JSON.stringify({
  schemaVersion: 1,
  currentKeyId: keyId,
  keys: { [keyId]: randomBytes(32).toString('base64url') },
}));
NODE
  } 2>/dev/null)"
  [[ -n "$CREDENTIAL_KEYRING" ]] || {
    warn "Credential keyring generation failed"
    exit 1
  }
  set_required_production_secret CREDENTIAL_KEYRING "$CREDENTIAL_KEYRING"
  unset CREDENTIAL_KEYRING
fi
if awk '{print $1}' <<<"$PRODUCTION_SECRETS" | grep -qx COMPUTER_HOST_TOKEN; then
  note "Preserving the existing COMPUTER_HOST_TOKEN so the deployed host keeps accepting the app Worker."
else
  say "Provision the shared secret the app Worker presents to the Computer host."
  COMPUTER_HOST_TOKEN="$(openssl rand -hex 32)"
  [[ -n "$COMPUTER_HOST_TOKEN" ]] || {
    warn "Computer host token generation failed"
    exit 1
  }
  set_required_production_secret COMPUTER_HOST_TOKEN "$COMPUTER_HOST_TOKEN"
  unset COMPUTER_HOST_TOKEN
fi
if awk '{print $1}' <<<"$PRODUCTION_SECRETS" | grep -qx ROUTINE_HOOK_SECRET; then
  note "Preserving the existing ROUTINE_HOOK_SECRET so already-issued Routine webhook keys keep verifying."
else
  say "Provision the secret every Routine webhook key is signed with."
  ROUTINE_HOOK_SECRET="$(openssl rand -hex 32)"
  [[ -n "$ROUTINE_HOOK_SECRET" ]] || {
    warn "Routine hook secret generation failed"
    exit 1
  }
  set_required_production_secret ROUTINE_HOOK_SECRET "$ROUTINE_HOOK_SECRET"
  unset ROUTINE_HOOK_SECRET
fi
if awk '{print $1}' <<<"$PRODUCTION_SECRETS" | grep -qx MACHINE_TOKEN_SECRET; then
  note "Preserving the existing MACHINE_TOKEN_SECRET so enrolled machines keep their tokens."
else
  say "Provision the secret every registered-machine token and pairing code is signed with."
  MACHINE_TOKEN_SECRET="$(openssl rand -hex 32)"
  [[ -n "$MACHINE_TOKEN_SECRET" ]] || {
    warn "Machine token secret generation failed"
    exit 1
  }
  set_required_production_secret MACHINE_TOKEN_SECRET "$MACHINE_TOKEN_SECRET"
  unset MACHINE_TOKEN_SECRET
fi
if awk '{print $1}' <<<"$PRODUCTION_SECRETS" | grep -qx APPLET_VIEWER_SECRET; then
  note "Preserving the existing APPLET_VIEWER_SECRET so open Applet pages keep their tokens."
else
  say "Provision the secret every Applet viewer token is signed with (ADR 0022)."
  APPLET_VIEWER_SECRET="$(openssl rand -hex 32)"
  [[ -n "$APPLET_VIEWER_SECRET" ]] || {
    warn "Applet viewer secret generation failed"
    exit 1
  }
  set_required_production_secret APPLET_VIEWER_SECRET "$APPLET_VIEWER_SECRET"
  unset APPLET_VIEWER_SECRET
fi
unset PRODUCTION_SECRETS

stage "GitHub: verify production configuration"
say "The repository already has the account ID, auth secret, app URL, and D1 ID."
if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  step "Checking environment secrets in ${GITHUB_REPOSITORY}…"
  gh secret list --repo "$GITHUB_REPOSITORY" --env "$GITHUB_ENVIRONMENT"
  step "Checking environment variables…"
  gh api "/repos/$GITHUB_REPOSITORY/environments/$GITHUB_ENVIRONMENT/variables" \
    --jq '.variables[] | [.name, .value] | @tsv'
else
  SKIPPED+=("GitHub verification (run gh auth login, then rerun)")
  warn "GitHub CLI is not authenticated, so verification was skipped"
fi
say "After this branch merges, CI deploys the app to https://bot.frockbot.com."
pause "Press Enter to finish."

finish
