/// FrockBot's own brand: the words, characters and updates that make the
/// client package FrockBot rather than another product (ADR 0038).
library;

import 'package:flutter/painting.dart';
import 'package:frockbot_client/frockbot_client.dart';

const frockbotBrand = ClientBrand(
  productName: 'FrockBot',
  builtInModelName: 'Frock AI',
  defaultCharacterId: 'pixel',
  releaseChannel: ClientReleaseChannel.shorebird,
  characters: [
    CharacterDefinition(
      'pixel',
      'Pixel',
      Color(0xfffc85ae),
      Color(0xffa95d75),
      Color(0xfffcf6e3),
      ink: CharacterInk(
        canvasWidth: 640,
        canvasHeight: 760,
        left: 98,
        top: 113,
        width: 447,
        height: 585,
      ),
      rive: 'assets/characters/pixel.riv',
      still: 'assets/characters/pixel.png',
      voice: 'Schedar',
    ),
    CharacterDefinition(
      'guardian',
      'Guardian',
      Color(0xff3c3543),
      Color(0xff211d26),
      Color(0xffffeee0),
      ink: CharacterInk(
        canvasWidth: 457,
        canvasHeight: 615,
        left: 25,
        top: 119,
        width: 421,
        height: 464,
      ),
      rive: 'assets/characters/guardian.riv',
      still: 'assets/characters/guardian.png',
      voice: 'Orus',
    ),
    CharacterDefinition(
      'sunny',
      'Sunny',
      Color(0xffffc928),
      Color(0xffd99a00),
      Color(0xfffff6df),
      ink: CharacterInk(
        canvasWidth: 457,
        canvasHeight: 615,
        left: 11,
        top: 146,
        width: 421,
        height: 438,
      ),
      rive: 'assets/characters/sunny.riv',
      still: 'assets/characters/sunny.png',
      voice: 'Puck',
    ),
    CharacterDefinition(
      'chill',
      'Chill',
      Color(0xff59c7ff),
      Color(0xff258dc5),
      Color(0xfff4fbff),
      ink: CharacterInk(
        canvasWidth: 457,
        canvasHeight: 615,
        left: 29,
        top: 98,
        width: 402,
        height: 491,
      ),
      rive: 'assets/characters/chill.riv',
      still: 'assets/characters/chill.png',
      voice: 'Callirrhoe',
    ),
    CharacterDefinition(
      'nudge',
      'Nudge',
      Color(0xffff8b27),
      Color(0xffc95b12),
      Color(0xfffff4e9),
      ink: CharacterInk(
        canvasWidth: 457,
        canvasHeight: 615,
        left: 29,
        top: 191,
        width: 403,
        height: 400,
      ),
      rive: 'assets/characters/nudge.riv',
      still: 'assets/characters/nudge.png',
      voice: 'Achird',
    ),
    CharacterDefinition(
      'fox',
      'Fox',
      Color(0xffef6b4a),
      Color(0xffae402b),
      Color(0xfffff0dc),
      ink: CharacterInk(
        canvasWidth: 457,
        canvasHeight: 615,
        left: 17,
        top: 134,
        width: 423,
        height: 459,
      ),
      rive: 'assets/characters/fox.riv',
      still: 'assets/characters/fox.png',
      voice: 'Zubenelgenubi',
    ),
    CharacterDefinition(
      'dog',
      'Dog',
      Color(0xffdca258),
      Color(0xffb67c39),
      Color(0xfffff1d3),
      ink: CharacterInk(
        canvasWidth: 457,
        canvasHeight: 615,
        left: 28,
        top: 24,
        width: 362,
        height: 568,
      ),
      rive: 'assets/characters/dog.riv',
      still: 'assets/characters/dog.png',
      voice: 'Sulafat',
    ),
    CharacterDefinition(
      'goat',
      'Goat',
      Color(0xffd8c8ab),
      Color(0xff9d8968),
      Color(0xfffff8e8),
      ink: CharacterInk(
        canvasWidth: 457,
        canvasHeight: 615,
        left: 19,
        top: 70,
        width: 420,
        height: 520,
      ),
      rive: 'assets/characters/goat.riv',
      still: 'assets/characters/goat.png',
      voice: 'Gacrux',
    ),
    CharacterDefinition(
      'cow',
      'Cow',
      Color(0xfff4eee4),
      Color(0xffb9a99a),
      Color(0xfffff8e8),
      ink: CharacterInk(
        canvasWidth: 457,
        canvasHeight: 615,
        left: 18,
        top: 176,
        width: 425,
        height: 416,
      ),
      rive: 'assets/characters/cow.riv',
      still: 'assets/characters/cow.png',
      voice: 'Vindemiatrix',
    ),
    CharacterDefinition(
      'cat',
      'Cat',
      Color(0xff8b72d9),
      Color(0xff5942a0),
      Color(0xfffff2dc),
      ink: CharacterInk(
        canvasWidth: 457,
        canvasHeight: 615,
        left: 25,
        top: 102,
        width: 411,
        height: 487,
      ),
      rive: 'assets/characters/cat.riv',
      still: 'assets/characters/cat.png',
      voice: 'Despina',
    ),
    CharacterDefinition(
      'rabbit',
      'Rabbit',
      Color(0xffd7b9f1),
      Color(0xff9d78be),
      Color(0xfffff7e8),
      ink: CharacterInk(
        canvasWidth: 457,
        canvasHeight: 615,
        left: 49,
        top: 31,
        width: 358,
        height: 560,
      ),
      rive: 'assets/characters/rabbit.riv',
      still: 'assets/characters/rabbit.png',
      voice: 'Leda',
    ),
  ],
);
