// Generated from packages/plugin-flock/assets/manifest.json by
// scripts/generate-dart-sheep-layers.ts. Do not edit.

/// The base sheep every Bot starts from.
const sheepCanonical = 'canonical';

/// Background ids; the image is `background-<id>.webp`.
const sheepBackgrounds = <String>[
  'hot-pink',
  'electric-blue',
  'lime-green',
  'canary-yellow',
  'bright-orange',
  'vivid-purple',
];

/// Every layer node's parent. A root (the neutral option of a tree) has
/// no parent and draws nothing; a chosen node draws itself and every
/// ancestor below the root, ancestors first.
const sheepLayerParents = <String, String?>{
  // upper
  'upper-neutral': null,
  'terracotta-beanie': 'upper-neutral',
  'canary-rain-cap': 'upper-neutral',
  'matte-black-top-hat': 'upper-neutral',
  'navy-wizard-hat': 'upper-neutral',
  'coral-bucket-hat': 'upper-neutral',
  'lilac-flower-crown': 'upper-neutral',
  'canary-party-hat': 'upper-neutral',
  'forest-ranger-fedora': 'upper-neutral',
  'purple-witch-hat': 'upper-neutral',
  'blue-sailor-cap': 'upper-neutral',
  'gold-royal-crown': 'upper-neutral',
  'chef-toque': 'upper-neutral',
  'rainbow-propeller-cap': 'upper-neutral',
  'burgundy-beret': 'upper-neutral',
  'silver-space-helmet': 'upper-neutral',
  'straw-boater': 'upper-neutral',
  'graduation-cap': 'upper-neutral',
  'orange-hard-hat': 'upper-neutral',
  'ranger-fedora-feather': 'forest-ranger-fedora',
  'witch-hat-moon': 'purple-witch-hat',
  'sailor-cap-anchor': 'blue-sailor-cap',
  'royal-crown-rubies': 'gold-royal-crown',
  'white-tennis-visor': 'upper-neutral',
  // middle
  'middle-neutral': null,
  'teal-glasses': 'middle-neutral',
  'amber-glasses': 'middle-neutral',
  'plum-glasses': 'middle-neutral',
  'rose-heart-sunglasses': 'middle-neutral',
  'bronze-aviator-goggles': 'middle-neutral',
  'cobalt-round-glasses': 'middle-neutral',
  'green-square-glasses': 'middle-neutral',
  'yellow-star-glasses': 'middle-neutral',
  'tortoiseshell-readers': 'middle-neutral',
  'rainbow-visor': 'middle-neutral',
  'violet-masquerade-mask': 'middle-neutral',
  'white-snow-goggles': 'middle-neutral',
  'retro-3d-glasses': 'middle-neutral',
  // lower
  'lower-neutral': null,
  'teal-bowtie': 'lower-neutral',
  'purple-scarf': 'lower-neutral',
  'red-polka-bowtie': 'lower-neutral',
  'turquoise-bandana': 'lower-neutral',
  'gold-sun-medallion': 'lower-neutral',
  'emerald-necktie': 'lower-neutral',
  'leather-bell': 'lower-neutral',
};

/// Readable names for the avatar editor.
const sheepLayerLabels = <String, String>{
  'background-hot-pink': 'Hot pink',
  'background-electric-blue': 'Electric blue',
  'background-lime-green': 'Lime green',
  'background-canary-yellow': 'Canary yellow',
  'background-bright-orange': 'Bright orange',
  'background-vivid-purple': 'Vivid purple',
  'upper-neutral': 'No headwear',
  'terracotta-beanie': 'Terracotta beanie',
  'canary-rain-cap': 'Canary rain cap',
  'matte-black-top-hat': 'Matte-black top hat',
  'navy-wizard-hat': 'Navy wizard hat',
  'coral-bucket-hat': 'Coral bucket hat',
  'lilac-flower-crown': 'Lilac flower crown',
  'canary-party-hat': 'Canary party hat',
  'forest-ranger-fedora': 'Forest ranger fedora',
  'purple-witch-hat': 'Purple witch hat',
  'blue-sailor-cap': 'Blue sailor cap',
  'gold-royal-crown': 'Gold royal crown',
  'chef-toque': 'Chef toque',
  'rainbow-propeller-cap': 'Rainbow propeller cap',
  'burgundy-beret': 'Burgundy beret',
  'silver-space-helmet': 'Silver space helmet',
  'straw-boater': 'Straw boater',
  'graduation-cap': 'Graduation cap',
  'orange-hard-hat': 'Orange hard hat',
  'ranger-fedora-feather': 'Ranger fedora + feather',
  'witch-hat-moon': 'Witch hat + moon brooch',
  'sailor-cap-anchor': 'Sailor cap + anchor pin',
  'royal-crown-rubies': 'Royal crown + rubies',
  'white-tennis-visor': 'White tennis visor',
  'middle-neutral': 'No glasses',
  'teal-glasses': 'Teal glasses',
  'amber-glasses': 'Amber round glasses',
  'plum-glasses': 'Plum cat-eye glasses',
  'rose-heart-sunglasses': 'Rose heart sunglasses',
  'bronze-aviator-goggles': 'Bronze aviator goggles',
  'cobalt-round-glasses': 'Cobalt round glasses',
  'green-square-glasses': 'Green square glasses',
  'yellow-star-glasses': 'Yellow star glasses',
  'tortoiseshell-readers': 'Tortoiseshell reading glasses',
  'rainbow-visor': 'Rainbow visor',
  'violet-masquerade-mask': 'Violet masquerade mask',
  'white-snow-goggles': 'White snow goggles',
  'retro-3d-glasses': 'Retro 3D glasses',
  'lower-neutral': 'No neckwear',
  'teal-bowtie': 'Teal satin bow tie',
  'purple-scarf': 'Purple silk scarf',
  'red-polka-bowtie': 'Red polka-dot bow tie',
  'turquoise-bandana': 'Turquoise bandana',
  'gold-sun-medallion': 'Gold sun medallion collar',
  'emerald-necktie': 'Emerald necktie',
  'leather-bell': 'Leather bell collar',
};
